### ISSUE TITLE
Having parentheses in argument for UiSelector breaks with 'unclosed paren in expression'

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium-uiautomator2-server#122]
Method consumeFunctionCall() in uiautomator2/utils/UiSelectorParser.java makes sure that there are same number of ( and ) and extracts the arguments between them. 

But if I want to send a query that contains a parentheses that is not closed, like:

    new UiSelector().text("A(B")

This should be allowed. Or at least function should verify if parentheses are escaped and let those pass.

Any suggestion for me to search text on Android other than xpath?

@imurchie

Thanks

**Comment by jlipps** [comment]
Yeah, this highlights the weakness of reimplementing ui selector parsing. Probably we could fix this though, what do you think @mykola-mokhnach @vmaxim?

**Comment by tfcardoso** [comment]
I dislike so much xpath, that I'll simple re-implement my methods using .textMatches and replace the text with ( or ) with . in the regex :-)
