### ISSUE TITLE
Execute UiAutomator commands within appium script

### ISSUE THREAD

**Issue by igalep** [appium/appium-uiautomator2-server#127]
I was wonder if there a way to execute UiAutomator commands straight from appium test ?

The only API I do see is "findElementByAndroidUIAutomator" which expect to get a return value from uiutomator (UiScrollable / UiObject) in order to look after it.

In my flow I trying to execute a UiScrollable().flingBackward() command which returns boolean value ...

Is there a way to achieve it ?

**Comment by imurchie** [comment]
No. The `findElementByAndroidUIAutomator` expects a UIAutomator command that will find an element, and returns that. The UIAutomator code needs to eventually return a UIObject instance.

There is no generic method for executing UIAutomator code.
