### ISSUE TITLE
uiautomator2 server apks reinstall every time

### ISSUE THREAD

**Issue by WindInMay524** [appium/appium-uiautomator2-server#174]
**Question**:
when I start appium with uiautomator2-driver, these two uiautomator server apks will reinstall again,this install thing needed to be click "continue to install" menu by hand initiativly,how can I solve it
**Version**:
appium:1.8.1
android:7.1.1
**Server log**:
https://gist.github.com/WindInMay524/68f63393d53b1acc33157a82cb1f0e33
![image](https://user-images.githubusercontent.com/38344643/41757602-ae2fa0d4-7615-11e8-8ab6-15d898df0778.png)

**Comment by markmarijnissen** [comment]
Can't you remember the choice? This worked for me (Redmi 4)

**Comment by WindInMay524** [comment]
I have closed USB verified application installation
![image](https://user-images.githubusercontent.com/38344643/43448045-74169482-94df-11e8-9ed9-1bce8decc408.png)

**Comment by imurchie** [comment]
This should be fixed now. Only when the server versions don't match is there an upgrade.
