### ISSUE TITLE
some w3c action raise error after a1ca0f2adbe9189d43e4cdb39efd1af1378e1828

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-uiautomator2-server#214]
When I tested w3c actions ( https://github.com/appium/appium-uiautomator2-server/pull/210 ), I faced below error.
https://gist.github.com/KazuCocoa/717ee0469a1f312cd55310d904824544

A comment in the gist is logs which work well.

I git bisected. Then, I found the error started after a1ca0f2adbe9189d43e4cdb39efd1af1378e1828

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-server/pull/205/files#diff-16d4f22093c4ac93bef589a3f14479a3R128 returns `false`

**Comment by mykola-mokhnach** [comment]
Thanks @KazuCocoa 
I'll try to fix that in https://github.com/appium/appium-uiautomator2-server/pull/210

**Comment by KazuCocoa** [comment]
When I roughly reverted to `upDownBalance` logic from `nonHoveringProps.length` one, it worked in my local.

thanks! @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
I've pushed a fix. Can you please try again with the new commit?

**Comment by KazuCocoa** [comment]
Worked perfectly with https://github.com/appium/appium-uiautomator2-server/pull/210/commits/1642184e3a6a13e19b2097c81ab0a2e7eb3534d6 👍
