### ISSUE TITLE
/element/active not implemented.

### ISSUE THREAD

**Issue by scyiwei** [appium/appium-uiautomator2-server#228]
When using driver.switch_to.active_element to get the active element, it returns 404 in the server side.

**Comment by omy13** [comment]
I don't know if your problem is the request. But the api documentation is wrong. The service is a GET and not a POST. Try changing it to fix the 404 .

[http://appium.io/docs/en/commands/element/other/active/](url)

**Comment by KazuCocoa** [comment]
Yes, it should work.
POST was old MJWONWP. W3C should be GET as you addressed.
