### ISSUE TITLE
Need a way to disable logging

### ISSUE THREAD

**Issue by sshock** [appium/appium-uiautomator2-server#241]
Is there any way to disable logging other than commenting it out and creating my own build?

**Comment by imurchie** [comment]
The Appium server has a flag, `--log-level`, which can be set higher to get less logging. See the documentation here: http://appium.io/docs/en/writing-running-appium/server-args/

**Comment by sshock** [comment]
I'm talking about the logging from io.appium.uiautomator2.server app that runs on the android device (that shows up in logcat on the device), not the logging from appium server (node program).

**Comment by sshock** [comment]
I think if the `io.appium.uiautomator2.utils.Logger` were updated to first check `android.util.Log.isLoggable()` before each call to `Log.x`, then I would be able to control the logging via `setprop` or with `/data/local.prop` as described here:

https://developer.android.com/reference/android/util/Log#isLoggable(java.lang.String,%20int)

**Comment by mykola-mokhnach** [comment]
@sshock Feel free to add a PR. This should be a simple change

**Comment by sshock** [comment]
@mykola-mokhnach Sounds good.  I will see if I get around to it sometime this week ;)

Note that the default level is INFO, so if I understand correctly, after making this change VERBOSE and DEBUG will no longer be logged by default, and if someone wants those they will need to use setprop and/or specify in /data/local.prop.  So we may want to consider ways to raise awareness about this so people aren't totally caught off guard.
