### ISSUE TITLE
issue with uiautomator2

### ISSUE THREAD

**Issue by anilkn72** [appium/appium-uiautomator2-server#252]
With the use of appium able to enter the string using sendkeys in selenium and select the full string displayed , however using uiautomatior2 it pastes the string in the textbox and the string doesnot display below that field to select from it.

Please help me with this issue.

**Comment by KazuCocoa** [comment]
It depends on the selected element. uia2 calls setText in uiautomator framework at the end.
`mobile:type` or send commands may be alternative
https://appium.io/docs/en/commands/mobile-command/
