### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Mygod** [appium/appium-uiautomator2-server#27]
Find element by xpath with attribute selector doesn't work.

scrollable, checkable, clickable, longClickable always return false.

**Comment by sravanmedarapu** [comment]
@Mygod, Can you share the syntax that you have tried ?
I could see appropriate elements are returning [example](https://github.com/appium/java-client/blob/4b2dfd280860da3d1d0acf7e2c35b2cfd2e02aad/src/test/java/io/appium/java_client/android/AndroidElementTest.java#L43)

**Comment by Mygod** [comment]
I'm using java-client and `driver.findElements(By.xpath("//*[@enabled='true'"))` returns nothing.

Invoking `element.getAttribute("scrollable")` etc. always return `"false"`.

**Comment by Mygod** [comment]
So... any updates?

**Comment by sravanmedarapu** [comment]
Using appium-uiautomator2-driver v0.0.5 should fix the issue.

**Comment by Mygod** [comment]
Okay now it seems to return the same element (e.g. `581badc7-71f5-45ed-81b7-a9d964493373`) every time. :confused:

**Comment by sravanmedarapu** [comment]
What do you mean same element?  Can you share the sample code snippet to replicate or explain more?

**Comment by Mygod** [comment]
Sure. Here's the snippet.

    public static Stream<AbstractAction> getActions(TestManager manager) {
        return manager.getDriver().findElements(By.xpath("//*[@enabled='true']")).stream()
                .filter(element -> Boolean.parseBoolean(element.getAttribute("displayed")))
                .flatMap(element -> UiAction.getActions(manager, element));
    }

    private static Stream<UiAction> getActions(TestManager manager, MobileElement element) {
        LinkedList<UiAction> result = new LinkedList<>();
        if (Boolean.parseBoolean(element.getAttribute("scrollable"))) result.add(new Swipe(manager, element));
        if (Boolean.parseBoolean(element.getAttribute("checkable")) ||
                Boolean.parseBoolean(element.getAttribute("clickable"))) result.add(new Click(manager, element));
        if (Boolean.parseBoolean(element.getAttribute("longClickable")))
            result.add(new LongClick(manager, element));
        return result.stream();
    }

I put a breakpoint at the latter method and from the debugger I can see that element is always the same one (the ID is the same).

**Comment by sravanmedarapu** [comment]
@Mygod, Can you try with appium-uiautomator2-driver v0.0.6 ?

**Comment by Mygod** [comment]
Great! It finally works. :+1:

**Comment by Mygod** [comment]
Oh btw could you fix this as well? https://github.com/appium/appium/issues/6974

**Comment by sravanmedarapu** [comment]
Typically UiAutomator interacts with elements which are displayed on the screen and will not be able to identify any elements which are not in the current view, unlike web browser interactions.

In fact Node info of Page Source will not contain info about displayed status, below is the typical Node  and attributes.

`<android.widget.TextView index="1" text="Settings" class="android.widget.TextView" package="com.android.launcher3" content-desc="Settings" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[384,777][572,974]" resource-id="" instance="1"/>`

**Comment by Mygod** [comment]
I see. Thanks.
