### ISSUE TITLE
Hard to accept such an inefficient appium in Android！Here is an optimization suggestion

### ISSUE THREAD

**Issue by zengxiaoshi** [appium/appium-uiautomator2-server#277]
The culprit is so many "Device.waitForIdle()" when findElement.
Can we delete some redundant  “Device.waitForIdle()”？

**Comment by imurchie** [comment]
Which `Device.waitForIdle()` calls are redundant? When finding elements it is necessary to wait for things to settle or else they will not be found.

Have you experimented with removing them? If so, we are always open to PRs.

**Comment by zengxiaoshi** [comment]
> Which `Device.waitForIdle()` calls are redundant? When finding elements it is necessary to wait for things to settle or else they will not be found.
> 
> Have you experimented with removing them? If so, we are always open to PRs.
----------------------------------------------------------------------------------------------
I know we need to wait for the current activity to idle before finding elements,
and I think `Device.waitForIdle()` is called one times is enough.
(1) `Device.waitForIdle()` will be called until timeout(10s) which activity has dynamic elements;
(2) `Device.waitForIdle()` has been called more than 3 times when finding elements in appium-uiautomator2-server ;
(3) From the above:
	1. activity has dynamic elements > 30s
	2. static activity must be settle less than 10s, if it more than 10s, I think it is a bad application.

**Comment by mykola-mokhnach** [comment]
> static activity must be settle less than 10s, if it more than 10s, I think it is a bad application.

The history confirms there are too many bad applications. It is possible to customise the default idle timeout by setting the `waitForIdleTimeout` setting

**Comment by zengxiaoshi** [comment]
> > static activity must be settle less than 10s, if it more than 10s, I think it is a bad application.
> 
> The history confirms there are too many bad applications. It is possible to customise the default idle timeout by setting the `waitForIdleTimeout` setting
---------------------------------------------------------------------------
For most of the applications, one call to “waitForIdle” is enough.
If it is a bad application, they can set timeout in their test cases, rather than appium's.
There are too many people who can't understand why appium so slow.
Except for modify the source code of appium-uiautomator2-server,  we can't set timeout  for  “waitForIdle” .

**Comment by mykola-mokhnach** [comment]
the fix has been merged to appium@beta
