### ISSUE TITLE
Refresh operation in getElementFromCache does not include the original element's context

### ISSUE THREAD

**Issue by kelly987654** [appium/appium-uiautomator2-server#280]
When interacting with an element that has gone stale, the ui-automator server attempts to reacquire the element using the element's original locator. However the query used to refresh the element does not include the context that may have been included with the element's original query. As a result, the re-acquired element found by the incomplete query may be a different element. This can result in the user unknowingly interacting with a different element than expected/originally acquired.

Code of interest is in KnownElements.java, getElementFromCache.

Example to reproduce (based on simple page layout below):
1. Get element by accessibility id: 'containerId'
2. Get element by className: android.widget.Button, including a context elementId acquired in step 1
3. Perform some operation so the elements on the page go stale (e.g. scroll page up and down)
4. Attempt to tap on the element acquired in Step 2 - The element is reacquired and matches on the topButton instead, resulting on a 'tap' on the topButton instead of the expected button.

```
<page>
  <topButton className='android.widget.Button'/>
  <container content-desc='containerId'>
    <buttonInContainer className='android.widget.Button'/>
  </container>
</page>
```

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta

**Comment by kelly987654** [comment]
Thank you!
