### ISSUE TITLE
Issue in finding element fromParent using findelementByAndroidUIAutomation with uiautomator2

### ISSUE THREAD

**Issue by sreddy61286** [appium/appium-uiautomator2-server#282]
Trying to find text view under target parent in Appium inspector and it returns no element found.

**locator used:** 
> new UiSelector().className("android.widget.TextView").fromParent(new UiSelector().resourceId("com.afollestad.materialdialogssample:id/action_bar"))

> O/p: no element found

If I use following selector string it works
`new UiSelector().resourceId("com.afollestad.materialdialogssample:id/action_bar").childSelector(new UiSelector().className("android.widget.TextView"))`

**Can somebody help me to find the problem. If possible help me with "fromParent" example.**

Sample code:

public class SampleTest {
  private AndroidDriver driver;
  @Before
  public void setUp() throws MalformedURLException {
    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setCapability("platformVersion", "9.0");
    desiredCapabilities.setCapability("deviceName", "Pixel API 28");
    desiredCapabilities.setCapability("udid", "emulator-5554");
    desiredCapabilities.setCapability("app", "/Users/sudhakar/Downloads/md.apk");
    desiredCapabilities.setCapability("noReset", true);
    desiredCapabilities.setCapability("platformName", "android");
    desiredCapabilities.setCapability("automationName", "UiAutomator2");
    URL remoteUrl = new URL("http://localhost:4723/wd/hub");
    driver = new AndroidDriver(remoteUrl, desiredCapabilities);
  }

  @Test
  public void sampleTest() {
    List<MobileElement> els1 = (MobileElement) driver.findElementsByAndroidUIAutomator("new UiSelector().className(\"android.widget.TextView\").fromParent(new UiSelector().resourceId(\"com.afollestad.materialdialogssample:id/action_bar\"))");
  }

  @After
  public void tearDown() {
    driver.quit();
  }
}

**Attached .apk file and screenshots for reference** 
[md.apk.zip](https://github.com/appium/appium-uiautomator2-server/files/3247884/md.apk.zip)
<img width="1440" alt="TargetElement" src="https://user-images.githubusercontent.com/44253007/58807581-2d852080-85cd-11e9-9a10-7763cc6458fa.png">
<img width="1434" alt="Parent" src="https://user-images.githubusercontent.com/44253007/58807567-26f6a900-85cd-11e9-94ed-af30bc879433.png">
<img width="1431" alt="Selector" src="https://user-images.githubusercontent.com/44253007/58807580-2d852080-85cd-11e9-9c20-182daf2a0235.png">
<img width="1428" alt="Result" src="https://user-images.githubusercontent.com/44253007/58807570-26f6a900-85cd-11e9-8ad6-27de7babdd4b.png">

**Appium inspector capabilities:**
{
  "platformVersion": "9.0",
  "deviceName": "Pixel API 28",
  "udid": "emulator-5554",
  "app": "/Users/sudhakar/Downloads/md.apk",
  "noReset": true,
  "platformName": "android",
  "automationName": "UiAutomator2"
}

**Comment by sreddy61286** [comment]
Can somebody check for "fromParent" behaviour in uiautomator2 please. I try to use locator as followed and it didn't work for me

new UiSelector().className("android.widget.TextView").fromParent(new UiSelector().resourceId("com.afollestad.materialdialogssample:id/action_bar"))

**Comment by imurchie** [comment]
@sreddy61286 Are you trying with the latest Appium beta? This has been fixed.

**Comment by sreddy61286** [comment]
I'll check that with Appium Beta. FYI I was using Appium Desktop version 1.13.

**Comment by sreddy61286** [comment]
And Thanks a lot @imurchie for your response.

**Comment by QAthulhu** [comment]
Hi, sorry for bumping this but I'm experiencing the same issue but on v1.11.0

Is this fix is only available on later versions?

**Comment by KazuCocoa** [comment]
Yes, Appium did not port fixes for older versions/branches.

(and closes as fixed https://github.com/appium/appium-uiautomator2-server/issues/282#issuecomment-500813664 )

**Comment by sudha61286** [comment]
> @sreddy61286 Are you trying with the latest Appium beta? This has been fixed.

Hi imurchie,
 I tried on Appium 1.15.1 and still issue is reproducible.
