### ISSUE TITLE
Unable to ScrollDown

### ISSUE THREAD

**Issue by Salvadorgs** [appium/appium-uiautomator2-server#290]
Not sure if this is correct, but from my understanding, it should be scrolling down and is not doing it. The Appium Version I have is:

		
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>4.1.2</version>
		</dependency>

*************************************************************************************
driver.findElementByXPath("//*[@class='android.view.View']").click();
		((AndroidDriver<WebElement>) driver).findElementByAndroidUIAutomator("new UiScrollable(new UiSelector()).scrollIntoView(text(\"*Políticas disponibles a través del sitio www.metlife.com.mx\"));");

Is not giving me an Error but also is not Scrolling Down. Can someone please help me with this?
Thank you in advance.

**Comment by Lalesia** [comment]
Hi,
You have to specify what is scrollable,
e.g. new UiSelector().className(someName) or just pass parameter true if the you want to scroll the page itself:
new UiScrollable(true).scrollIntoView(text("*Políticas disponibles a través del sitio www.metlife.com.mx\"));
Or
new UiScrollable(new UiSelector().className(someClass)).scrollIntoView(text("*Políticas disponibles a través del sitio www.metlife.com.mx\"));

**Comment by Salvadorgs** [comment]
Awesome, I had fixed already but thank you for the replay!.
