### ISSUE TITLE
content-desc not found for certain elements

### ISSUE THREAD

**Issue by ACoolUsername** [appium/appium-uiautomator2-server#304]
This issue started appearing when I updated my app to use Xamarin Forms 4.1 from 4.0, but I don't think the issue is just in Xamarin. Some tests I have stopped being able to find a Xamarin Picker element by automation id/content-desc. I checked manually using uiautomatorviewer.bat and it could find the content-desc using the updated Xamarin, which made me think the issue wasn't entirely rooted in Xamarin. I updated to the most recent version of uiautomator2 server, but the issue was still there.

**Comment by mykola-mokhnach** [comment]
UIAutomator framework only sees the page source generated for the accessibility. Which means if your app under test does not provide this info to the accessibility framework then Appium has no way to show these values as well.

**Comment by ACoolUsername** [comment]
Thanks for getting back to me. 

As far as I know I am setting the automation id correctly. There's no complicated binding for the picker's automation id, it's just a value. And the content-desc was as expected when I was using the 4.0 Xamarin Forms: I could see its content-desc in the page source using uiautomator2 server and manually with uiautomatorviewer.bat. However, when I updated Xamarin Forms, the uiautomator2 server page source no longer contained the content-desc of the picker, but it was present when I manually checked uiautomatorviewer.bat. 

However, with your comment in mind, I did some more testing with the updated Xamarin Forms and uiautomatorviewer.bat and made the following observations:

- The picker's content-desc is present for the first device screenshot, but is not visible in a second one.
- The picker's content-desc is not present in the first device screenshot if I wait several seconds before taking it. 
- The picker's content-desc is not present in the first device screenshot if I perform a small scroll before taking the screenshot.

With this new information, I think my initial conclusion was incorrect. Since the content-desc can be missing in both uiautomatorviewer device screenshots and with uiautomator2 server, the issue most likely is not in uiautomator2 server, but in the Xamarin Forms update. Somehow the accessibility is losing the content-desc of the picker when the page is updated, or it's being overwritten. If you know how that could potentially happen I'd appreciate any help you could give. Regardless, unless you think otherwise, it seems safe to close this issue, and I can take this up with Xamarin Forms.

**Comment by jlipps** [comment]
Thanks for the in depth explanation, let us know what you hear over there.
