### ISSUE TITLE
 The latest version does not run on androiud version 8.0 or 7.0.

### ISSUE THREAD

**Issue by KIM-KOOKHYUN** [appium/appium-uiautomator2-server#305]
The latest version does not run on android version 8.0 or 7.0.

Is it impossible?
If there is a solution, let us know that.

**Comment by Zaykona** [comment]
Hi , have the same issue with android 7. 
Error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/natallia/Library/Android/sdk/platform-tools/adb -H localhost -P 5037 -s emulator-5556 install -r /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' exited with code 1'; Stderr: 'adb: failed to install /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1400829298.tmp/base.apk: META-INF/CERT.SF has invalid digest for javax/annotation/meta/Exclusive.java in /data/app/vmdl1400829298.tmp/base.apk]'; Code: '1'

**Comment by KazuCocoa** [comment]
If you used android sdk 29, such sign error could happen because of the apksigner bug.
Please try with sdk 28 or 30. (I usually use 28 tho)
