### ISSUE TITLE
 Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by shibupanda** [appium/appium-uiautomator2-server#310]
Hi,

Appium: 1.14.2
uiautomator2 server: 3.7.0
java client: 7.2.0
Issue frequency: 100
Device: Vivo_Y17_9.0.0

Weare encountered the issue(socket hangup) in the middle of the execution most specific to VIVO devices due to uiautomator2 server getting killed in between the execution. 
From the analysis we have found that Vivo devices is trying to kill the background process. Please add your input on this if you'll find some more info in device logs.

Please find the appium logs:
https://gist.github.com/shibupanda/48052feaebc2132bde00b21bcf812e8f

Device Logs:
https://gist.github.com/shibupanda/8fec8e75cd1a82537e564b33df0921eb

Could you please help us in this as we are completely blocked for Vivo devices.

**Comment by KazuCocoa** [comment]
The VIVO system perhaps kills the uia2 server since I guess the app is not downloaded from Google Play. (or somewhere valid by the VIVO)

Is there any settings to allow apps installed via adb in developer options or somewhere?

```
11-13 11:41:51.559  1074  1468 D AES     : AEEIOCTL_GET/SET_SF_STATE IOCTL,cmd= 1074294797, lParam=0. 
11-13 11:41:51.559  1074  1468 D AES     : AEEIOCTL_RT_MON_Kick IOCTL,cmd= 2147774474, lParam=300. 
11-13 11:41:51.562  1364 13121 I _V_ABE  : uid = 10146 name = io.appium.uiautomator2.server
11-13 11:41:51.563  1364  4505 I _V_ABE  : POWER_EXCEPT_IN....
11-13 11:41:51.563  1364  4505 I _V_ABE  : PowerApp [uid=10146, power=0.17110416666666667, name=io.appium.uiautomator2.server, mobileActiveCount=0, cpuTime=9100, gpsTime=0, wakelockTime=34, wifiRxBytes=110100, wifiTxBytes=0, mobileActive=0, mobileRxBytes=0, mobileTxBytes=0, requestCode=0, timeAlarm=null, lauchCount=0, isCheck=false, appName=null, notifiId=0, highPower=9.0, highPowerTag=1]
11-13 11:41:51.563  1364  4505 I _V_ABE  :  ---------------- EasyShare mDataPool = false
11-13 11:41:51.564  1364  4505 I _V_ABE  :  conditionKillStrategy io.appium.uiautomator2.server
11-13 11:41:51.565  1364  4505 I _V_ABE  :  isNeedToKillApp =  io.appium.uiautomator2.server
11-13 11:41:51.565  1364  4505 I _V_ABE  : io.appium.uiautomator2.server maliceSystem is null !!! 
11-13 11:41:51.565  1364  4505 I _V_ABE  : io.appium.uiautomator2.server is want to kill = 1 level = 3
11-13 11:41:51.577   415   415 W hwcomposer: [JOB] (2) copyvds is ture but vir buffer format is not HAL_PIXEL_FORMAT_YV12  
11-13 11:41:51.578  7677 11234 I BufferQueueProducer: [minicap](this:0x7252853000,id:0,api:1,p:446,c:7677) queueBuffer: slot 2 is dropped, handle=0x725283eb40
11-13 11:41:51.581   583 10578 V MediaCodec: -- Looking at startdata. presentation 45278566, start 1223143190918, so drop entry
11-13 11:41:51.581   583 10578 V MediaCodec: -- Looking at startdata. presentation 45445400, start 1223176914688, so nothing to pair
11-13 11:41:51.581   583 10578 I chatty  : uid=1013(media) NPDecoder-CL identical 1 line
11-13 11:41:51.582   583 10578 V MediaCodec: -- Looking at startdata. presentation 45445400, start 1223176914688, so nothing to pair
11-13 11:41:51.582   583 10578 V MediaCodec: -- Looking at startdata. presentation 45445400, start 1223176914688, so  match entry
```

**Comment by varundtsfi** [comment]
Hi @KazuCocoa  Might be possible that server is not signed by that device keystone.  Because It's killed on vivo very frequently.
There is a command which will allow the uiautomator server in background 

```
adb shell cmd appops set io.appium.uiautomator2.server RUN_IN_BACKGROUND allow 
But this is also not working. 
```

Can we signed the server with system keystore . I don't know much about that. That's why I am asking..

Please provide your valuable input.

**Comment by KazuCocoa** [comment]
hm, thanks.

`useKeystore` https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md and relevant caps help to change the signing of UIA2 server

**Comment by shibupanda** [comment]
@KazuCocoa @varundtsfi 
I tried to sign uiautomator2 server using custom capabilities still getting same.

**Comment by KazuCocoa** [comment]
Perhaps, you should ask it for VIVO developer support to run development apps in the background.
I do not know well about VIVO specific limitations.

btw, you can check the app has been restricted by Android OS as _App Info -> Battery_ in settings.
https://stackoverflow.com/questions/46315849/android-o-settings-to-enable-background-restriction-for-applications/52707377
The feature is Android native feature. You probably can relax the restriction if _io.appium.uiautomator2.server_ is limited by default.

**Comment by shibupanda** [comment]
Thanks @KazuCocoa it helped. We have enabled servers in battery consumption settings and by using skipServerInstallation = true we can avoid socket hangup.

**Comment by NagarajLakshatti** [comment]
i have tryed this solution still i am getting socket hangup can any one help me? 
Real device details
Android vivo 1807 and version  8.1.0

**Comment by Prasanth-chockalingam** [comment]
Hey can you please tell me the steps to do this....
And skipServerInstallation = true is this a capability?

**Comment by ManojBadiger** [comment]
Stop appium server and execute below commands

`adb uninstall io.appium.uiautomator2.server`
`adb uninstall io.appium.uiautomator2.server.test`

**Comment by BettyOk** [comment]
@ManojBadiger Thanks alot, it worked
