### ISSUE TITLE
Is there a tool suitable for Uiautomatorviewer of uiautomator2?

### ISSUE THREAD

**Issue by studyJavaForLive** [appium/appium-uiautomator2-server#320]
Hello, 
I have did an upgrade. 
Appium Desktop version 1.4 to 1.13
uiautomator version 1 to 2
Problem:
The information obtained by uiautomator2 is different from that of uiautomator1. 
1. Hidden element information of the Android device can not be obtained
2. Some element information is disapper compare to original
What parameters are configured to obtain complete information?
Can you give me a hand? Please.

**Comment by KazuCocoa** [comment]
`allowInvisibleElements` https://appium.io/docs/en/advanced-concepts/settings/ will help for the hidden element.

Each element information depends on Android UiAutomator2 system. Thus, if it meant some elements had no information than UiAutomator1, it is because Android does not provide them in most cases.

**Comment by studyJavaForLive** [comment]
Thank you very much!  I will try to set the UIA2's settings.

**Comment by studyJavaForLive** [comment]
Thanks again!
Now, I can obtain complete information.
Via setting:
"ignoreUnimportantViews",false
"allowInvisibleElements",true
But, I find a new phenomenon appearance.

List<WebElement> list = driver.findElementsByClassName("android.view.View"); 
The size of list is 100. 
However, the information obtained via driver.getPageSource() contains over 600 element(calss name is "android.view.View"). Is UIA2 limited it?

**Comment by studyJavaForLive** [comment]
@KazuCocoa

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/appium-uiautomator2-server/blob/c534718535d9541592087e489adad220e15d46b0/app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java#L48 is to prevent OOM
