### ISSUE TITLE
appium-uiautomator2-server-v4.3.0.apk' does not exist or is not accessible

### ISSUE THREAD

**Issue by arroyoc** [appium/appium-uiautomator2-server#327]
I recently upgrade from appium 1.14 to appium 1.16. After the update I am getting this error:

`Original error: An unknown server-side error occurred while processing the command. Original error: The file at 'C:\Users\username\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.3.0.apk' does not exist or is not accessible
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'desktopName', ip: 'ipaddress', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: AndroidDriver`

The problem is that it is looking for `appium-uiautomator2-server-v4.3.0.apk` but `appium-uiautomator2-server-v4.3.0.apk` doesn't exist.

After viewing the `'C:\Users\username\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\` folder I see that the apk version is different. The apk that is in that location is `appium-uiautomator2-server-v4.5.2.apk`

If I set my capability as `caps.setCapability("automationName", "uiautomator1");` I don't get the error and it works. However, uiautomator1 is deprecated and uiautomator2 is now default with 1.16.

**Comment by resial2** [comment]
Hello,

I got this error when I update appium and tried to run the automation before stop all appium services and nodes of selenium grid (who was configured with appium 1.15.1). After restart all services (including the appium-nodes in selenium grid) and tried again, I was able to execute the tests.

**Comment by KazuCocoa** [comment]
On your environment, did `appium-uiautomator2-server-v4.3.0.apk` exist?
If not, please make sure `npm install` first since the most possible case is missing the apk by npm install or a security software lock/remove the app.

**Comment by arroyoc** [comment]
@KazuCocoa 
`appium-uiautomator2-server-v4.3.0.apk` does not exist on my environment. When I check I only see `appium-uiautomator2-server-v4.5.2.apk`. But it is looking for `appium-uiautomator2-server-v4.3.0.apk`.

**Comment by KazuCocoa** [comment]
Hm, I guess your uia2 driver has the previous files because of npm cache etc.
Could you uninstall your local appium once and reinstall it?

**Comment by KazuCocoa** [comment]
Please remove the local dependencies and re-install appium first for this kind of error.
Let us know if this does not resolve the issue.
