### ISSUE TITLE
[Proposal] Add support for reading SMS/OTP content

### ISSUE THREAD

**Issue by navneet-kumar** [appium/appium-uiautomator2-server#333]
I have seen many request for reading SMS/OTP using various(flaky) ways to read SMS.
why can't we add an API to read the SMS content and respond back ?

I can investigate and raise a PR if there is no valid reason for not to have it.

open for suggestions/requests.

**Comment by mykola-mokhnach** [comment]
@navneet-kumar Would something like https://github.com/appium/io.appium.settings/pull/55 work for you?

**Comment by navneet-kumar** [comment]
@mykola-mokhnach Yes this will do the magic on android side !  
how about iOS ? can we do the similar thing there as well ?

**Comment by mykola-mokhnach** [comment]
no, Apple does not provide any APIs for that. The only thing you could do is to open SMS using "usual" accessibility interactions. At least all iPhones have the same user interface

**Comment by KazuCocoa** [comment]
`mobile: listSms` command https://github.com/search?q=org%3Aappium+listSms&type=Code on current the latest beta.
