### ISSUE TITLE
Find element by xpath is starting at the wrong root node

### ISSUE THREAD

**Issue by Mygod** [appium/appium-uiautomator2-server#34]
`/hierarchy/android.widget.FrameLayout[1]/...` wouldn't work in this automation. Instead I need to write `/android.widget.FrameLayout[1]/...`.

**Comment by sravanmedarapu** [comment]
technically `uiautomator2-driver` has new xpath implementation. coming to the issue `/hierarchy/` is something which is injected by earlier([bootstrap](https://github.com/appium/appium-android-bootstrap/blob/e0df190e35baccf31b4e2af81db75cff580631a1/bootstrap/src/io/appium/uiautomator/core/AccessibilityNodeInfoDumper.java#L73)) implementations that is something we have avoided here. 

Not sure about the impact of existing scripts. 

@bootstraponline/ @imurchie  Can you share your opinion on this, should we also add `/hierarchy/` element tree ?

**Comment by jlipps** [comment]
@sravanmedarapu if there's a `<hierarchy>` root tag in the original appium android support, we added it because there was no root node and xml requires one

**Comment by Mygod** [comment]
There's a hierarchy tag in dumped source in uiautomator2 too. At least it should be consistent imho.

**Comment by sravanmedarapu** [comment]
@Mygod, Using appium-uiautomator2-driver v0.0.8 should fix the issue.

**Comment by Mygod** [comment]
Hmm. It seems that both of these two work fine. Thanks!

**Comment by Mygod** [comment]
Oh wait my fault. Only the `hierarchy` works now (which is great :+1:)
