### ISSUE TITLE
25% slowdown in uiautomator2 server version 2.6.0

### ISSUE THREAD

**Issue by sshock** [appium/appium-uiautomator2-server#358]
We've been using Appium 1.9.1 (uiautomator2 1.18.0) for almost 2 years now (bad! we need to update!).

Unfortunately, something changed after Appium 1.9.1 that caused most of our automation jobs to take about 25% longer (which is a big deal for us).  I tested every version of Appium up to the latest (1.17.1) and it never goes back down to the speed of 1.9.1.

Here is a table showing the slowdown after Appium 1.9.1 that can be seen in almost every automation job type except Job A.  (Each job was ran three times; the times are in seconds).

Released | Appium Version | Job A | Job B | Job C | Job D | Job E
-- | -- | -- | -- | -- | -- | --
Sep 2018 | 1.9.1 | 27,30,30 | 43,43,47 | 43,44,43 | 49,44,46 | 47,45,49
Nov 2018 | 1.10.0 | (install failed) ||||
Feb 2019 | 1.11.0 | 33,32,32 | 97,82,110 | 63,61,64 | 73,63,74 | 56,62,56
Mar 2019 | 1.12.0 | 63,35,39 | 93,54,60 | 89,52,? | 88,63,65 | 75,59,57
May 2019 | 1.13.0 | 31,30,31 | 66,56,60 | 39,52,46 | 59,73,61 | 59,65,64
Aug 2019 | 1.14.2 | 37,30,38 | 64,58,67 | 51,48,43 | 62,59,58 | 57,59,58
Oct 2019 | 1.15.1 | 30,29,31 | 78,63,79 | 46,46,45 | 57,59,55 | 61,54,56
Dec 2019 | 1.16.0 | 72,29,29 | 103,45,64 | 75,45,48 | 89,59,53 | 85,61,56
Mar 2020 | 1.17.0 | 30,31,28 | 71,71,72 | 48,46,? | 72,58,54 | 52,56,57
May 2020 | 1.17.1 | 32,28,32 | 68,61,61 | n/a | 67,62,57 | 58,58,52

So I decided to test uiautomator2-server from version 1.18.0 to 3.1.1 (the versions that correspond to Appium 1.9.1 to 1.11.0).  I tested with Job B, but using a faster device.  This test indicates that the slowdown occurred in version 2.6.0 of appium-uiautomator2-server.

version | status
-- | --
1.18.0 | GOOD (30s)
1.19.0 | GOOD (29s)
1.19.1 | GOOD (30s)
1.20.0 | OK (39s, 38s, 35s)
2.0.0 | GOOD (33s)
2.1.0 | GOOD (32s)
2.2.0 | GOOD (31s)
2.3.0 | GOOD (30s)
2.5.0 | GOOD (30s)
2.6.0 | BAD (64s, 39s, 42s)  <=== PROBLEM INTRODUCED HERE
2.7.0 | BAD (42s, ...)
2.8.0 | BAD (58s, 55s, 43s)
3.0.0 | Could not proxy command to remote server. Original error: Error: read ECONNRESET
3.1.0 | BAD? (33s, ??, 43s)
3.1.1 | BAD (69s, 45s, 44s)

Here are the changes from 2.5.0 to 2.6.0 that are under suspicion:

* 640d284 Update getText to return an empty value instead of null and bounds/displayed calculation (#218)
* 04ec84b Add AX tree refresh before getting the page source (#216)
* e7799e8 Update tests for more visibility (#215)
* f53c830 Update motion events generation logic (#210)
* 919d382 Avoid refreshing accessibility twice while executing xpath queries (#213)
* cc9b767 Remove the redundant uiElementIndex attribute from the source tree (#211)

Can you provide any insight into which of those changes is the likely culprit, and is there anything we can do about it?  I know a lot has changed since that time (it was 1.5 years ago) that makes it harder to know where to go from here, but I'm hoping if we can get a little more understanding or hints on what to do from here, maybe we can find a bug in one of the commits above or we can have an explanation for what we might be doing wrong on our side that somehow is ok in versions before 2.6.0 but not ok after.

I admit that our automation jobs perform a lot of finding of elements by xpath, which I know according to the docs is slow and not recommended, but most of the time we don't have a resource-id or content-desc to search by and everything is working fast enough for us with Appium 1.9.1.  We would like to be able to update without taking what feels like an unnecessary penalty (or is there is a reason behind why it had to slow down?).

Without some additional insight and a fix or workaround, I fear we will be stuck on Appium 1.9.1 forever, which is obviously not a good place to be in :(

**Comment by KazuCocoa** [comment]
Could be, but not sure all cases.

```
     * reason for explicit method, in some cases google UiAutomator2 throwing exception
     * while calling waitForIdle() which is causing appium UiAutomator2 server to fall in
     * unexpected behaviour.
     * for more info please refer
     * https://code.google.com/p/android/issues/detail?id=73297
```
https://github.com/appium/appium-uiautomator2-server/blob/c0d2d45740a2f9d05cf0e6c3b7b1a19e2f85d1b1/app/src/main/java/io/appium/uiautomator2/utils/Device.java#L96-L117

> Does the refreshAccessibilityCache() absolutely need to do a Device.waitForIdle();?

Maybe we encountered such error or added it for safe.
The value can customise via https://appium.io/docs/en/advanced-concepts/settings/ `waitForIdleTimeout`

**Comment by sshock** [comment]
@KazuCocoa In my case, I don't think tweaking the `waitForIdleTimeout` would help, unless I set it to a very tiny value close to 0, because assuming this is where the delay is coming from, it's not because of a few large times, but rather many hundreds or thousands of times getting called.

Unfortunately, I assume setting it to 0 is also not an option because that would introduce all kinds of incomplete screen / stale element problems just like completely getting rid of it would.

Unless...., I could set it to 0 most of the time but then also make explicit calls to waitForIdle() (with a non-zero timeout) in key areas of my own code like right after clicking a button when I know I need to wait for a screen transition.  That could work, right?  And is that something I can do right now?

**Comment by sshock** [comment]
I did some more digging by testing custom builds and found out something I didn't expected.

First I tried removing the call to refreshAccessibilityCache(), but that was a no-go; the automation job couldn't even get past the first page.

Then I tried removing the call to Device.waitForIdle() inside refreshAccessibilityCache(), which didn't appear to cause any problems, but also did not improve performance.

Finally, I went back and tested each commit between 2.5.0 and 2.6.0, which showed this:


Time (seconds) | Commit
-- | --
71, 72 | * d936c6d (tag: v2.6.0) 2.6.0
87, 71, 73 | * 640d284 Update getText to return an empty value instead of null and bounds/displayed calculation (#218)
47, 53, 52 | * 04ec84b Add AX tree refresh before getting the page source (#216)
(skipped) | * e7799e8 Update tests for more visibility (#215)
50, 48 | * f53c830 Update motion events generation logic (#210)
56, 49 | * 919d382 Avoid refreshing accessibility twice while executing xpath queries (#213)
47, 44 | * cc9b767 Remove the redundant uiElementIndex attribute from the source tree (#211)
51, 50 | * 9d5313e (tag: v2.5.0) 2.5.0

So... it very much looks like the real culprit is 640d284.  I was not expecting that.

@mykola-mokhnach do you have insight into why this commit could cause such a noticeable slowdown?

**Comment by mykola-mokhnach** [comment]
How about https://github.com/appium/appium-uiautomator2-server/commit/640d284095b9080f59650ad105e7e7c416b9ce6f#diff-76ee56434e83c035586d4a6c1f853f8cR138 ?

**Comment by mykola-mokhnach** [comment]
Please check if https://github.com/appium/appium-uiautomator2-server/pull/360 makes the xml lookup process faster for you

**Comment by sshock** [comment]
Thanks for the quick turn-around @mykola-mokhnach.  I will be so happy if #360 speeds things up!  I'll test it out on Monday.

In the meantime, just a couple questions if you don't mind:

1. What exactly did that change to line 138 do, and why can't it simply be undone?  Why is `element.exists() ` not sufficient to represent the DISPLAYED attribute?  Also, where does getAttribute(DISPLAYED) get called from?  Does that get called a lot?

2. I hope I am just reading this wrong, but the PR says "only include the actually queried attributes into the source xml".  Does that mean if I find an element by matching a certain attribute then the resulting element will only have that one attribute?  For example, if I find an element by xpath `//android.widget.TextView[@text="hello"]`, then the element returned will only have `element.text`, and not any other attributes?  I hope not because we often search by one attribute (like resource-id) and then look at other attributes (like text and index) on the found element.

Thanks for bearing with me!

**Comment by mykola-mokhnach** [comment]
> What exactly did that change to line 138 do, and why can't it simply be undone? Why is element.exists() not sufficient to represent the DISPLAYED attribute? Also, where does getAttribute(DISPLAYED) get called from? Does that get called a lot?

`exists` itself is not enough in some cases (e.g. displayed might be returned as `true` for invisible elements without that check)

It is called for each element while building the page source.

> I hope I am just reading this wrong, but the PR says "only include the actually queried attributes into the source xml". Does that mean if I find an element by matching a certain attribute then the resulting element will only have that one attribute? For example, if I find an element by xpath //android.widget.TextView[@text="hello"], then the element returned will only have element.text, and not any other attributes? I hope not because we often search by one attribute (like resource-id) and then look at other attributes (like text and index) on the found element.

The change is completely transparent to an end user. Everything will work completely as it was working before.

**Comment by sshock** [comment]
Oh good.  Thank you so much for explaining that.

**Comment by sshock** [comment]
Check out the initial results here:
https://github.com/appium/appium-uiautomator2-server/pull/360#issuecomment-644449486

It definitely looks like a speed-up to me, although maybe not quite as much of a speed-up as I was hoping for ;)  But I really need to test with more job types to see and I'll do that tomorrow.

Also, I have to remind myself that although there was a huge performance difference from Appium 1.9.1 to 1.11.0 (for Job B at least), Appium 1.9.1 compared to the current code does not have as wide of a performance gap.

I was curious though to see if I could find out which part of 640d284 exactly was causing such a noticeable slowdown, so I did some more testing using uiautomator v2.6.0 as a starting point, and I found something interesting:

time (seconds) | codebase
-- | --
128, 72, 73 | * 2.6.0 (unmodified)
74, 68, 70 | * Revert change to case DISPLAYED   (didn't help)
73, 69 | * Comment out put(attributes, Attribute.DISPLAYED, node.isVisibleToUser());   (didn't help)
56, 59, 46 | * Comment out put(attributes, Attribute.BOUNDS, AccessibilityNodeInfoHelpers.getVisibleBounds(node).toShortString());
53, 52, 53 | * Comment out the "Find the visible bounds of our first scrollable ancestor" block in getVisibleBounds()

Turns out the "Find the visible bounds of our first scrollable ancestor" for loop with recursive call to check for ancestors in getVisibleBounds() appears to be the major culrprit for the slowdown in v2.6.0.

Unfortunately, when testing with the latest code in master (version 4.8.3), commenting out that block seemed to have no noticeable effect on performance.  If there was any effect it was very small.  I am really baffled as to why that code makes such a difference with the code from 1.5 years ago, but with the current code it doesn't.

It's too bad because I was starting to get excited that perhaps if we could combine #360 with also some way of removing or speeding up the ancestor node checking in here for bounds, maybe we could end up in a really good place.

I'll plan on doing some more tests with all our job types tomorrow, and maybe that will reveal better whether doing something with that is also worthwhile, or if we all we need is #360.

**Comment by sshock** [comment]
Here is a table with more timing results that I just added to #360 , but below I include another row that includes commenting out that block in getVisibleBounds().

uiaut2 version | Job A | Job B | Job C | Job D | Job E
-- | -- | -- | -- | -- | --
4.5.5 | 32,28,32 | 68,61,61 | 64,50,55 | 67,62,57 | 58,58,52
4.8.3 | 32,29,29 | 80,68,59 | 52,53,52 | 58,59,64 | 59,59,58
xml_attr branch | 31,31,27 | 58,52,56 | 57,51,52 | 66,58,57 | 68,51,51
don't check ancestors | 29,36,29 | 70,48,50 | 53,50,49 | 56,53,52 | 58,60,56

It's hard to say for sure if commenting out that block helped; I think it did, but only a little bit.

Unfortunately, the long story short is I am back to the drawing board because neither #360 nor commenting out that block have resulted in getting these job types completely back to where they were in Appium 1.9.1 (uiautomator2-server 1.18.0).  At the most I think we can say that with these changes the overall slowdown is at best only a 15% slowdown instead of a 25% slowdown.

So..., I think we are making progress, but still haven't really nailed it.

**Comment by sshock** [comment]
@mykola-mokhnach any ideas on how to speed up getVisibleBounds() while still being able to maintain correctness?  The change to look at ancestor nodes does adversely affect some of our job types.  Is there a chance getVisibleBounds() is getting called multiple times on the same ancestor, and if so could that Rect be cached or something?  For example, if my scene tree has N elements in it, then an operation that requires populating the bounds attribute on every element would be O(n*m) time complexity because it has to get every node M times (where a node has M descendants) instead of just once.

@KazuCocoa @mykola-mokhnach I've also been doing some more testing with timing logs that leads me to believe up to 25% of the time in my jobs is being spent in `Device.waitForIdle()`.  If I want to set the waitForIdleTimeout to 0 before making a bunch of calls to findElements, and then change it back after I've found what I want, can I then somehow make a direct call to Device.waitForIdle()?

I have a `transition` method that gets call between screens that repeatedly calls findElements() until an expected element for a possible next screen is found, and I'm wondering if I can set the waitForIdleTimeout to 0 during most of that transition method, but to make it safer I then want to do a Device.waitForIdle() once at the end (and maybe once at the beginning).

Thanks!

**Comment by mykola-mokhnach** [comment]
You could change idle timeout at any point of time, since it's a setting, not a capability.

Regarding visible bounds - I don't know any other way to change the stuff. It makes sense to use hybrid approach if your application is react-native based. It should be much faster then.

**Comment by sshock** [comment]
Thanks @mykola-mokhnach .  Yeah, I knew I can change the waitForIdle timeout at any time.  My question about that is is there a way to make it call waitForIdle() directly, or to achieve that would I have to do something silly like make a call to findElements() with some bogus xpath that I don't really care about finding?

Regarding visible bounds, if there's no way to speed it up by caching Rects or anything, perhaps instead could we consider adding a setting so that I could turn off the ancestor searching if I don't care about the improved accuracy?

**Comment by mykola-mokhnach** [comment]
> Yeah, I knew I can change the waitForIdle timeout at any time. My question about that is is there a way that I can call waitForIdle() directly, or to achieve that would I have to do something silly like make a call to findElements() with some bogus xpath that I don't really care about finding?

I'm not quite sure what to advice on that.

> Regarding visible bounds, if there's no way to speed it up by caching Rects or anything, perhaps instead could we consider adding a setting so that I could turn off the ancestor searching if I don't care about the improved accuracy?

Yes, this could be an option

**Comment by sshock** [comment]
> > Regarding visible bounds, if there's no way to speed it up by caching Rects or anything, perhaps instead could we consider adding a setting so that I could turn off the ancestor searching if I don't care about the improved accuracy?
> 
> Yes, this could be an option

sweet, thanks so much!

**Comment by sshock** [comment]
I did a bunch more tests to verify how much of a difference we see when setting waitForIdleTimeout to 0 and when we disable ancestor checking in getVisibleBounds().

Appium ver | UiAutomator2 ver | Job Q | Job R | Job S | Job T | Job U | Job V
-- | -- | -- | -- | -- | -- | -- | --
1.9.1 | 1.18.0 | *63,30,37 | 43,35,33 | 60,55,54 | 46,45,51 | 54,49,54 | 55,47
1.17.1 | 4.9.0 | 43,31,31 | 39,36,36 | 66,58,59 | 56,52,58 | 58,58,62 | 61,54,74
1.17.1 | 4.9.0 + 0 idle wait | 28,40,26 | 45,41,46 | 56,57,53 | 54,62,54 | 53,46,60 | 56,50,55
1.17.1 | 4.9.0 + 0 idle wait - bounds ancestors | 28,25,26 | 41,42,33 | 53,52,49 | 51,49,49 | 47,42,46 | 53,52,49
1.9.1 | 1.18.0 + 0 idle wait | 34,25,25 | 36,32,34 | 49,49,50 | 47,38,42 | 45,36,40 | 54,50,43

Interpreting the times above:
1. *When the first number is significantly higher then the next two, please ignore.
    * From the beginning I've noticed a pattern where the first job may take longer after re-installing uiautomator2.
1. There is a noticeable slowdown from 1.18.0 to 4.9.0, seen in the 2nd row, especially in job types S, T, U, and V.  And this is what we want to solve.
1. There is a noticeable speed-up in job types S, U, V seen in the third row by setting the idle wait to 0.  (Confusingly, job type R actually got slower, but I'll ignore that for now.)
1. There is a very noticeable speed-up in job types R, S, T, U, and V seen in the fourth row by turning off ancestor checking in the getVisibleBounds().
1. The final row shows how fast we could get even with the old Appium, but luckily with these two changes in place, the fourth comes pretty close to that, so I believe with these two changes we will be able to proceed and finally upgrade!

**Comment by sshock** [comment]
I've found another performance problem when upgrading appium.  We don't run this job type very often, but it is a test that works by tapping keys on the virtual keyboard (using TouchAction.tap).

With appium 1.9.1 it was very fast and couple type several characters a second.  With appium 1.17.1 and the latest uiautomator2 here, it only enters about 2 characters a second.

Also, setting waitForIdleTimeout to 0 with this job type didn't help and actually made things a worse (not entering correct characters).

@mykola-mokhnach Do you or anyone have any ideas on this, or workarounds I can try?  Also, let me know if you want me to create a new issue rather than continue the discussion going here.

**Comment by mykola-mokhnach** [comment]
yes, it makes sense to create a new issue and also provide the actual code and the client logs

**Comment by sshock** [comment]
ok, I created a new issue for the single tap slowdown: https://github.com/appium/appium-uiautomator2-server/issues/365

I'll go ahead and close this issue now.

**Comment by tzah4748** [comment]
#175 - not the same but might be related.
