### ISSUE TITLE
Make sense? `.../window/:windowHandle/size`

### ISSUE THREAD

**Issue by electricbubble** [appium/appium-uiautomator2-server#359]
Although it can work.

```bash
--> GET http://localhost:6790/wd/hub/session/__UUID__/window/:windowHandle/size

<-- GET http://localhost:6790/wd/hub/session/__UUID__/window/:windowHandle/size 200 3.013314ms
{"sessionId":"937bfc87-de84-474d-b23e-783f53efbed4","value":{"height":1280,"width":800}}
```

Would that be better?
```
"/wd/hub/session/:sessionId/window/size"
```

https://github.com/appium/appium-uiautomator2-server/blob/c0d2d45740a2f9d05cf0e6c3b7b1a19e2f85d1b1/app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java#L166

https://github.com/appium/appium-uiautomator2-server/blob/c0d2d45740a2f9d05cf0e6c3b7b1a19e2f85d1b1/app/src/main/java/io/appium/uiautomator2/handler/GetDeviceSize.java#L37-L43

**Comment by KazuCocoa** [comment]
If you want to propose a new Appium specific route, it's better to add `appium` in the path such as `/wd/hub/session/:sessionId/appium/window/size`

Btw, https://www.w3.org/TR/webdriver1/ already defines `/window/rect` maybe as the same as your intention. It is available via 
https://github.com/appium/appium-uiautomator2-driver/blob/9c314cc1803efad42c451d54b566ea4615e41e1f/lib/commands/general.js#L94-L102 for UIA2 server.
So, I don't think we should add a new route which is not in W3C while the same value can get via W3C spec.
