### ISSUE TITLE
Xcode 12, iOS 14, Appium 1.18.0-2,Mac OS-- unable to launch start inspector session from appium desktop

### ISSUE THREAD

**Issue by sravanisathavalli** [appium/appium-uiautomator2-server#383]
Hi, 

After upgrading to iOS 14 and xcode 12, I am not able to launch appium inspector. I get the error 

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**But if I am trying to run my test cases from IDE by starting the appium from terminal Webdriveragent is successfully installed on my phone and the test passes.**

I follow the steps in many posts to do the following

npm uninstall carthage
brew uninstall carthage
brew install carthage

and then navigated to cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
  and ran the command
carthage bootstrap --platform iOS\,tvOS and i get the same error
*** No Cartfile.resolved found, updating dependencies
Failed to read file or folder at /usr/local/Cellar/carthage/0.36.0/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/usr/local/Cellar/carthage/0.36.0/Cartfile, NSUnderlyingError=0x7fd7c1428fc0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}.

i have installed appium from npm and appium desktop from 
https://github.com/appium/appium-desktop/releases/tag/v1.18.0-2

How come my test case is passing but I am not able to launch appium inspector?

Please help.

**Comment by sravanisathavalli** [comment]
carthage bootstrap --platform iOS\,tvOS
*** Checking out CocoaAsyncSocket at "7.6.4"
*** Checking out YYCache at "1.1.2"
*** xcodebuild output can be found in /var/folders/9_/mj1x7t7x3jg33hp_x7p3bq200000gp/T/carthage-xcodebuild.aqSmMG.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.4"
*** Building scheme "YYCache tvOS" in YYCache.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/sravani/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/YYCache/1.1.2/Build/Intermediates.noindex/ArchiveIntermediates/YYCache\ tvOS/IntermediateBuildFilesPath/UninstalledProducts/appletvos/YYCache.framework/YYCache /Users/sravani/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/YYCache/1.1.2/Build/Products/Release-appletvsimulator/YYCache.framework/YYCache -output /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/YYCache.framework/YYCache

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/9_/mj1x7t7x3jg33hp_x7p3bq200000gp/T/carthage-xcodebuild.aqSmMG.log

**Comment by sravanisathavalli** [comment]
we have newly launched the app for apple watch and the Watch OS 7.0.

**Comment by KazuCocoa** [comment]
Deprecate of https://github.com/appium/appium-desktop/issues/1567
Appium Desktop does not have Xcode 12 (newer than beta 3) support version yet
