### ISSUE TITLE
How to get Error message of a text field .

### ISSUE THREAD

**Issue by techGuyAj** [appium/appium-uiautomator2-server#388]
HI.
  In my app, i have a create account activity where you can give a username and password. Now when i am testing that activity, i tried to get the error message when user enters already existing usename.  But i can't get it. I searached in element attributes also. But i can't find  it.  Please Help me to solve this issue.
       Thank you .

**Comment by KazuCocoa** [comment]
What the page source?
If nothing appeared on the source, perhaps Appium(UIAutomator2 framework) cannot get it.

A possible alternative is espresso driver then.

**Comment by techGuyAj** [comment]
> What the page source?
> If nothing appeared on the source, perhaps Appium(UIAutomator2 framework) cannot get it.
> 
> A possible alternative is espresso driver then.

yes. I am using UIAutomator2

**Comment by KazuCocoa** [comment]
> What the page source?

https://appium.io/docs/en/commands/session/source/

**Comment by techGuyAj** [comment]
> > What the page source?
> 
> https://appium.io/docs/en/commands/session/source/

[sourceNew.txt](https://github.com/appium/appium-uiautomator2-server/files/5383121/sourceNew.txt)

attached a text file which contains page source.
thank you

**Comment by KazuCocoa** [comment]
Is this line?

> <android.widget.TextView index="0" package="com.company.applicationName" class="android.widget.TextView" text="Already have account? " checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[548,1618][888,1662]" displayed="true" />

What was your query to find the element?

**Comment by techGuyAj** [comment]
> Is this line?
> 
> > <android.widget.TextView index="0" package="com.company.applicationName" class="android.widget.TextView" text="Already have account? " checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[548,1618][888,1662]" displayed="true" />
> 
> What was your query to find the element?

NO.
<android.widget.EditText index="1" package="com.company.applicationName" class="android.widget.EditText" text="rTest4@gmail.com" resource-id="com.company.applicationName:id/et_email" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" long-clickable="true" password="false" scrollable="false" selected="false" bounds="[238,742][938,879]" displayed="true" />

this is the text field which shows the error message "Email already exist,change Email or goto signin".

my code to get this element is:
js:
const element =await client.$('//android.widget.EditText[@resourceid="com.company.applicationName:id/et_email"]');

**Comment by KazuCocoa** [comment]
Can the message `Email already exist,change Email or goto signin` see on the page source when it appears to the view?

**Comment by KazuCocoa** [comment]
Then, probably UIAutomator2 cannot find it. Only Google can fix it.
Or Espresso driver may be an alternative.

**Comment by techGuyAj** [comment]
> Then, probably UIAutomator2 cannot find it. Only Google can fix it.
> Or Espresso driver may be an alternative.

i will check with Espresso driver.
Thank you.
