### ISSUE TITLE
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id

### ISSUE THREAD

**Issue by dev2314** [appium/appium-uiautomator2-server#397]
I am getting below error while executing my use case on emulator. 

Appium version : Appium v1.19.1

[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/Users/XXXXXX/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.android.apis'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/xxxxxxx/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/xxxxxxxx/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1607378676731 (14:04:36 GMT-0800 (Pacific Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Cannot verify the signature of '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk'. Original error: The JAVA_HOME environment variable must be set for Android Tools to work properly
[debug] [W3C]     at ADB.checkApkCert (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:267:11)
[debug] [W3C]     at UiAutomator2Server.installServerApk (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:94:13)
[debug] [W3C]     at AndroidUiautomator2Driver.initUiAutomator2Server (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:484:7)
[debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:379:5)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:224:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:366:35)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 990 ms - 997
[HTTP]

**Comment by KazuCocoa** [comment]
Probably https://github.com/appium/java-client/blob/master/docs/environment.md helps to fix the environment stuff

**Comment by dev2314** [comment]
Issue resolved after reinstalling appium server.
