### ISSUE TITLE
Screencast to url localhost:9100 similar to wda

### ISSUE THREAD

**Issue by tulasikrishan89** [appium/appium-uiautomator2-server#399]
Is their a solution that cast real time screen to websocket similar to webdriveragent open localhost:9100 after server start. If not any plans in adding it?

solution: appium service buffer screenshots to simulate as video through usb and open it in client browser

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-driver#mjpeg
