### ISSUE TITLE
How do I start server and create session with terminal commands and apis without using appium

### ISSUE THREAD

**Issue by tulasikrishan89** [appium/appium-uiautomator2-server#400]
I am starting server: 

**Execute in terminal**
adb shell am instrument -w io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner

**Result in terminal**
io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:

how do I establish a connection with specific device and control with api's

**Comment by KazuCocoa** [comment]
You can track steps in https://github.com/appium/appium-uiautomator2-driver/blob/b821a3cc301f4cb24abdea791ca1aa041fabe35b/lib/driver.js#L169 and https://github.com/appium/appium-uiautomator2-driver/blob/80216fce6c9850ef14ee27284de4ab5cb6094ac6/lib/uiautomator2.js#L193

`UiAutomator2Server` handles this server.

**Comment by tulasikrishan89** [comment]
some how able to success activating api calls by below steps:

Step 1: adb shell am instrument -w io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner
Step 2: adb -P 5037 -s 4c4757534c573398 forward tcp\:8200 tcp\:6790
Step 3:
 {{DEVICE_URL}}/wd/hub/session
Body: {
    "capabilities":{
        "platform": "LINUX",
        "webStorageEnabled": false,
        "takesScreenshot": true,
        "javascriptEnabled": true,
        "databaseEnabled": false,
        "networkConnectionEnabled": true,
        "locationContextEnabled": false,
        "desired":{"androidInstallTimeout":15000,
                    "autoLaunch":false,
                    "automationName":"uiautomator2",
                    "ensureWebviewsHavePages":true,
                    "fullReset":false,
                    "mjpegServerPort":9200,
                    "noReset":true,
                    "udid":"4c4757534c573398",
                    "newCommandTimeout":0,
                    "connectHardwareKeyboard":true}
    }
}



_**Still not able to get response from mjpegServer**_

**Comment by KazuCocoa** [comment]
Because probably your request did not satisfy with w3c spec format.

https://github.com/appium/appium-uiautomator2-server/blob/64ca1d9ac77f784b12228e0c96fc227b12beaff9/app/src/test/java/io/appium/uiautomator2/utils/w3c/W3CCapsUtilsTests.java#L34

**Comment by KazuCocoa** [comment]
uia2 is designed to launch via appium-uiautomator2-driver.
https://github.com/appium/appium-uiautomator2-driver/blob/80216fce6c9850ef14ee27284de4ab5cb6094ac6/lib/uiautomator2.js#L193 may help
