### ISSUE TITLE
Failure [INSTALL_PARSE_FAILED_BAD_MANIFEST] when installing 'appium-uiautomator2-server-v4.16.0.apk'.

### ISSUE THREAD

**Issue by HavenChen** [appium/appium-uiautomator2-server#401]
Failure [INSTALL_PARSE_FAILED_BAD_MANIFEST] occured when installing 'appium-uiautomator2-server-v4.16.0.apk'.

------------Error------------

[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell pm install -r /data/local/tmp/appium_cache/636ed67160f3b1a6f235f92ef18a89484785f800.apk'
[ADB] The installation of 'appium-uiautomator2-server-v4.16.0.apk' took 1144ms
[debug] [ADB] Install command stdout: pkg: /data/local/tmp/appium_cache/636ed67160f3b1a6f235f92ef18a89484785f800.apk
[debug] [ADB] Failure [INSTALL_PARSE_FAILED_BAD_MANIFEST]

-------Original Logs-------------

[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":"com.ccic.salesapp.activity.ActivityLoading","appPackage":"com.ccic.salesapp","deviceName":"22dbecce","ensureWebviewsHavePages":true,"noReset":true,"platformName":"Android","platformVersion":"6.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.ccic.salesapp.activity.ActivityLoading","appPackage":"com.ccic.salesapp","deviceName":"22dbecce","ensureWebviewsHavePages":true,"noReset":true,"platformName":"Android","platformVersion":"6.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1608713299556 (16:48:19 GMT+0800 (GMT+08:00))
[Appium]
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium]
[Appium]   The 'automationName' capability was not provided in the desired
[Appium]   capabilities for this Android session
[Appium]
[Appium]   Setting 'automationName=UiAutomator2' by default and using the
[Appium]   UiAutomator2 Driver
[Appium]
[Appium]   The next major version of Appium (2.x) will **require** the
[Appium]   'automationName' capability to be set for all sessions on all
[Appium]   platforms
[Appium]
[Appium]   In previous versions (Appium <= 1.13.x), the default was
[Appium]   'automationName=UiAutomator1'
[Appium]
[Appium]   If you wish to use that automation instead of UiAutomator2, please
[Appium]   add 'automationName=UiAutomator1' to your desired capabilities
[Appium]
[Appium]   For more information about drivers, please visit
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the
[Appium]   'Drivers' menu
[Appium]
[Appium] ======================================================================
[Appium]
[Appium] Appium v1.19.0-beta.0 creating new AndroidUiautomator2Driver (v1.60.0) session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "appActivity": "com.ccic.salesapp.activity.ActivityLoading",
[debug] [BaseDriver]   "appPackage": "com.ccic.salesapp",
[debug] [BaseDriver]   "deviceName": "22dbecce",
[debug] [BaseDriver]   "ensureWebviewsHavePages": true,
[debug] [BaseDriver]   "noReset": true,
[debug] [BaseDriver]   "platformName": "Android",
[debug] [BaseDriver]   "platformVersion": "6.0",
[debug] [BaseDriver]   "newCommandTimeout": 0,
[debug] [BaseDriver]   "connectHardwareKeyboard": true
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   connectHardwareKeyboard
[BaseDriver] Session created with session id: 61bd604a-4bf8-49c5-9f10-0722b648c763
[UiAutomator2] Starting 'com.ccic.salesapp' directly on the device
[ADB] Using 'adb.exe' from 'D:\android-sdk-windows\platform-tools\adb.exe'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"22dbecce","state":"device"}]
[AndroidDriver] Looking for a device with Android '6.0.0'
[debug] [ADB] Setting device id to 22dbecce
[ADB] Getting device platform version
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 6.0.1
[debug] [ADB] Setting device id to 22dbecce
[AndroidDriver] Using device: 22dbecce
[ADB] Using 'adb.exe' from 'D:\android-sdk-windows\platform-tools\adb.exe'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 start-server'
[debug] [ADB] Setting device id to 22dbecce
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 23
[debug] [ADB] Device API level: 23
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce wait-for-device'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell appops set io.appium.settings android:mock_location allow'
[debug] [Logcat] Starting logs capture with command: D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 22dbecce logcat -v threadtime
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to local port 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce forward tcp:8200 tcp:6790'
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Getting package info for 'io.appium.uiautomator2.server'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.16.0' >= '4.16.0')
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [ADB] Checking app cert for E:\ideaworkspace\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.16.0.apk
[ADB] Using 'apksigner.jar' from 'D:\android-sdk-windows\build-tools\28.0.3\lib\apksigner.jar'
[debug] [ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk1.8.0_221\\bin\\java.exe' -Xmx1024M -Xss1m -jar D:\\android-sdk-windows\\build-tools\\28.0.3\\lib\\apksigner.jar verify --print-certs E:\\ideaworkspace\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.16.0.apk
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] sha256 hash did match for 'appium-uiautomator2-server-v4.16.0.apk'
[ADB] 'E:\ideaworkspace\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.16.0.apk' is signed with the default certificate
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is not installed
[debug] [ADB] Checking app cert for E:\ideaworkspace\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk1.8.0_221\\bin\\java.exe' -Xmx1024M -Xss1m -jar D:\\android-sdk-windows\\build-tools\\28.0.3\\lib\\apksigner.jar verify --print-certs E:\\ideaworkspace\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] sha256 hash did match for 'appium-uiautomator2-server-debug-androidTest.apk'
[ADB] 'E:\ideaworkspace\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate
[UiAutomator2] Server packages are going to be (re)installed
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[debug] [ADB] The current Android API does not support extended ls options. Defaulting to no-options call
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell 'ls /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[debug] [ADB] The count of applications in the cache: 1
[ADB] The application at 'E:\ideaworkspace\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.16.0.apk' is already cached to '/data/local/tmp/appium_cache/636ed67160f3b1a6f235f92ef18a89484785f800.apk'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell touch -am /data/local/tmp/appium_cache/636ed67160f3b1a6f235f92ef18a89484785f800.apk'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell pm install -r /data/local/tmp/appium_cache/636ed67160f3b1a6f235f92ef18a89484785f800.apk'
[ADB] The installation of 'appium-uiautomator2-server-v4.16.0.apk' took 1144ms
[debug] [ADB] Install command stdout: pkg: /data/local/tmp/appium_cache/636ed67160f3b1a6f235f92ef18a89484785f800.apk
[debug] [ADB] Failure [INSTALL_PARSE_FAILED_BAD_MANIFEST]
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce shell am force-stop com.ccic.salesapp'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 22dbecce forward --remove tcp:8200'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1608713319004 (16:48:39 GMT+0800 (GMT+08:00))
[debug] [MJSONWP] Encountered internal error running command: Error: pkg: /data/local/tmp/appium_cache/636ed67160f3b1a6f235f92ef18a89484785f800.apk
[debug] [MJSONWP] Failure [INSTALL_PARSE_FAILED_BAD_MANIFEST]
[debug] [MJSONWP]     at ADB.install (E:\ideaworkspace\appium\node_modules\appium-adb\lib\tools\apk-utils.js:613:13)
[debug] [MJSONWP]     at UiAutomator2Server.installServerApk (E:\ideaworkspace\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:135:11)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.initUiAutomator2Server (E:\ideaworkspace\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:484:7)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.startUiAutomator2Session (E:\ideaworkspace\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:379:5)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.createSession (E:\ideaworkspace\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:224:7)
[debug] [MJSONWP]     at AppiumDriver.createSession (E:\ideaworkspace\appium\lib\appium.js:366:35)
[debug] [MJSONWP] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 19480 ms - 264
[HTTP]
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[debug] [HTTP] No route found for /wd/hub/session
[HTTP] <-- DELETE /wd/hub/session 404 12 ms - 211

**Comment by KazuCocoa** [comment]
-> https://github.com/appium/appium/issues/14969
