### ISSUE TITLE
"EnableMultipleWindow" not working

### ISSUE THREAD

**Issue by orangex** [appium/appium-uiautomator2-server#409]
## The problem
Uiautomator Server can not access the element on the window which is not active even if "EnableMultipleWindow" is set to "True".

## Environment
Appium version: 1.19.1
Node.js version : v12.8.1
Real device or emulator/simulator: real device(Sumsang A51 android 10)
UIAutomator server version: 4.15.0

##Details
I wrote a simple demo app to verify it. There is two window ,one is the default window ,the other one  is a popupwindow  on the bottom-right 
![image](https://user-images.githubusercontent.com/6096121/105681493-28a47b80-5f2c-11eb-97c4-be6849fb6976.png)
But when i try to locate the "NEXT" Button ,only one result is returned .
the button in popupwindow will be returned if the popupwindow'focus is set 
the button in center will be returned if the popupwindow'focus is not set 
In a word ,it looks like only the elements in the active window can be found. (Of course,"EnableMultipleWindow" is set to True)
![image](https://user-images.githubusercontent.com/6096121/105682810-dbc1a480-5f2d-11eb-9763-ecfeafc4f97a.png)

##Link to Appium logs
[appium-server-logs.txt](https://github.com/appium/appium-uiautomator2-server/files/5865338/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
We don't control the way controls are found - it's up to UaAutomator framework itself. Consider reporting the issue to Google.

As a workaround I would try to find the button by xpath

**Comment by orangex** [comment]
> We don't control the way controls are found - it's up to UaAutomator framework itself. Consider reporting the issue to Google.
> 
> As a workaround I would try to find the button by xpath

I tried and all the locater (xpath, class name ……) returns only one element . So ,maybe that's not a problem about UIA framework?

**Comment by Plinzen** [comment]
Hello @orangex , 

did you find a solution to your problem? Basically I have the same problem when using split screen.

**Comment by orangex** [comment]
@Plinzen  not yet  , I almost gave up

**Comment by KazuCocoa** [comment]
Did you try with settings api? `enableMultiWindows` https://github.com/appium/appium-uiautomator2-driver#settings-api

You tried via capabilities, but it was not valid capabilities.
```
[info] [35m[Appium][39m Appium v1.19.1 creating new AndroidUiautomator2Driver (v1.59.0) session
[info] [35m[Appium][39m Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "autoGrantPermissions": true,
[debug] [35m[BaseDriver][39m   "automationName": "UiAutomator2",
[debug] [35m[BaseDriver][39m   "enableMultiWindows": false,
[debug] [35m[BaseDriver][39m   "ensureWebviewsHavePages": true,
[debug] [35m[BaseDriver][39m   "noReset": false,
[debug] [35m[BaseDriver][39m   "noSign": true,
[debug] [35m[BaseDriver][39m   "platformName": "Android",
[debug] [35m[BaseDriver][39m   "udid": "R5CN507VWCF",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   enableMultiWindows
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: d2f445a7-7077-495b-abb4-ee3433236476
[info] [35m[UiAutomator2][39m Neither 'app' nor 'appPackage' was set. Starting UiAutomator2 without the target application
```

When you'd like to use as a capability, you should set as `settings[enableMultiWindows]` as https://appium.io/docs/en/writing-running-appium/caps/#update-settings

**Comment by Dor-bl** [comment]
@KazuCocoa Maybe we can close this one from 2021
