### ISSUE TITLE
Incorrect appium-uiautomator2-server .apk referenced in Appium 1.20.2

### ISSUE THREAD

**Issue by szymon-kazmierczak** [appium/appium-uiautomator2-server#412]
I'm trying to run tests with the c# client using Appium server 1.20.2, and the following error happens:

```
An unknown server-side error occurred while processing the command. Original error: The file at '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk' does not exist or is not accessible
```

I checked the directory and the specified apk is not there(`appium-uiautomator2-server-v4.15.0.apk`). The apk that i found is `appium-uiautomator2-server-v4.17.4.apk`

**Comment by KazuCocoa** [comment]
Did you clean install Appium once? (Meaning unisntall/install again)
My environment has 4.17.4 correctly.

Modules installed by `npm` could keep some older ones, so it is safe to uninstall the older one before install.

**Comment by szymon-kazmierczak** [comment]
I tried multiple times @KazuCocoa , sadly didnt work! Since it was a global installation, i removed entire `/usr/local/lib/node_modules/appium` and it reinstalled with the incorrect version.

**Comment by KazuCocoa** [comment]
I don't know why, but your npm environment failed to get the correct version addressed in https://github.com/appium/appium/blob/v1.20.2/npm-shrinkwrap.json#L4587-L4591
`npm install appium-uiautomator2-server@4.17.4` can get the correct version apk on my local. so package itself seems good.

You can try out non-global installation to ensure you can get the version first.

**Comment by szymon-kazmierczak** [comment]
I'll keep trying, has to be something on my end if it works for you, thanks for help! :)

**Comment by VeronikaProj** [comment]
@szymon-kazmierczak, have you found a solution?
I faced with the same problem on Appium server 1.22.2 (installed with npm 8.3.1)
