### ISSUE TITLE
server failed to start crashed in YeaLinkA30 device

### ISSUE THREAD

**Issue by cheffey** [appium/appium-uiautomator2-server#418]
server version: v4.15.0
logcat:
`--------- beginning of crash
03-31 14:53:11.738 32575 32575 F linker : CANNOT LINK EXECUTABLE "/vendor/bin/tloc_daemon": library "libloc_api_v02.so" not found
03-31 14:53:12.086 32587 32587 F linker : CANNOT LINK EXECUTABLE "/system/vendor/bin/netmgrd": library "com.quicinc.cne.constants@1.0.so" not found
--------- beginning of system
03-31 14:53:14.381 1867 20018 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10057 user=0: start instr
03-31 14:53:14.430 1867 1935 I ActivityManager: Start proc 32663:io.appium.uiautomator2.server/u0a57 for added application io.appium.uiautomator2.server
03-31 14:53:16.632 32663 32697 E AndroidRuntime: FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
03-31 14:53:16.632 32663 32697 E AndroidRuntime: Process: io.appium.uiautomator2.server, PID: 32663
03-31 14:53:16.632 32663 32697 E AndroidRuntime: java.lang.IllegalStateException: Cannot call disconnect() while connecting!
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at android.app.UiAutomation.disconnect(UiAutomation.java:283)
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at android.app.Instrumentation.finish(Instrumentation.java:244)
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:364)
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:412)
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:401)
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2152)
03-31 14:53:16.738 32763 32763 F linker : CANNOT LINK EXECUTABLE "/vendor/bin/tloc_daemon": library "libloc_api_v02.so" not found
03-31 14:53:16.743 1867 2764 I ActivityManager: Process io.appium.uiautomator2.server (pid 32663) has died: fore FGS
03-31 14:53:16.754 1867 2764 W ActivityManager: Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo

{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
03-31 14:53:16.754 1867 2764 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10057 user=0: finished inst
read: unexpected EOF!
`
Please offer your insight for us to solve this problem.

**Comment by KazuCocoa** [comment]
It seems Android internal itself got an issue. I think Appium can do nothing, unfortunately.

```
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at android.app.UiAutomation.disconnect(UiAutomation.java:283)
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at android.app.Instrumentation.finish(Instrumentation.java:244)
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:364)
03-31 14:53:16.632 32663 32697 E AndroidRuntime: at
```

Or the device has no expected library...? (In the case also can do nothing in Appium side, unfortunately)

```
03-31 14:53:11.738 32575 32575 F linker : CANNOT LINK EXECUTABLE "/vendor/bin/tloc_daemon": library "libloc_api_v02.so" not found
03-31 14:53:12.086 32587 32587 F linker : CANNOT LINK EXECUTABLE "/system/vendor/bin/netmgrd": library "com.quicinc.cne.constants@1.0.so" not found
```

**Comment by cheffey** [comment]
> It seems Android internal itself got an issue. I think Appium can do nothing, unfortunately.
> 
> ```
> 03-31 14:53:16.632 32663 32697 E AndroidRuntime: at android.app.UiAutomation.disconnect(UiAutomation.java:283)
> 03-31 14:53:16.632 32663 32697 E AndroidRuntime: at android.app.Instrumentation.finish(Instrumentation.java:244)
> 03-31 14:53:16.632 32663 32697 E AndroidRuntime: at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:364)
> 03-31 14:53:16.632 32663 32697 E AndroidRuntime: at
> ```
> 
> Or the device has no expected library...? (In the case also can do nothing in Appium side, unfortunately)
> 
> ```
> 03-31 14:53:11.738 32575 32575 F linker : CANNOT LINK EXECUTABLE "/vendor/bin/tloc_daemon": library "libloc_api_v02.so" not found
> 03-31 14:53:12.086 32587 32587 F linker : CANNOT LINK EXECUTABLE "/system/vendor/bin/netmgrd": library "com.quicinc.cne.constants@1.0.so" not found
> ```

Thanks for the fast response. I sense that the logcat tells us it does NOT have needed .so files. I'm not familiar with android development. Can this be solved by adding .so file when compiling the server? I wish I don't have to modify the device, because modifying it may make us miss bugs cause by lacking of that .so file.

**Comment by KazuCocoa** [comment]
> Can this be solved by adding .so file when compiling the server?

Do you mean when Appium compiles Appium/UIA2 server?
Probably this issue was runtime stuff. Then, only the manufacture can modify/fix this.

I don't have enough experience to develop Android devices, so this is just an assumption in the attached log.
