### ISSUE TITLE
Unable to Run Tests on Android - UiAutomator2 Server Crashes/Not Working 

### ISSUE THREAD

**Issue by ramgiteng** [appium/appium-uiautomator2-server#436]
Hello,

I am unable to run Appium tests on **real Android devices**. Please refer to the following log snippet.

**UIAutomator2 Logs**:
[UiAutomator2] Starting UIAutomator2 server 4.17.4
[UiAutomator2] Using UIAutomator2 server from '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.17.4.apk' and test from '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","42345a325a383498","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:52742/wd/hub/status] with no body
[WD Proxy] socket hang up
[debug] [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:52742/wd/hub/status] with no body
[WD Proxy] socket hang up
[debug] [Instrumentation] Error in startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server):
[debug] [Instrumentation] java.lang.ExceptionInInitializerError
[debug] [Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.<init>(MjpegScreenshotServer.java:41)
[debug] [Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.<init>(MjpegScreenshotServer.java:35)
[debug] [Instrumentation] 	at io.appium.uiautomator2.server.ServerInstrumentation.startMjpegServer(ServerInstrumentation.java:241)
[debug] [Instrumentation] 	at io.appium.uiautomator2.server.test.AppiumUiAutomator2Server.startServer(AppiumUiAutomator2Server.java:31)
[debug] [Instrumentation] 	at java.lang.reflect.Method.invoke(Native Method)
[debug] [Instrumentation] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[debug] [Instrumentation] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[debug] [Instrumentation] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[debug] [Instrumentation] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[debug] [Instrumentation] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[debug] [Instrumentation] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[debug] [Instrumentation] 	at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
[debug] [Instrumentation] 	at org.junit.runners.Suite.runChild(Suite.java:128)
[debug] [Instrumentation] 	at org.junit.runners.Suite.runChild(Suite.java:27)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[debug] [Instrumentation] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[debug] [Instrumentation] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[debug] [Instrumentation] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[debug] [Instrumentation] 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[debug] [Instrumentation] 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
[debug] [Instrumentation] 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2214)
[debug] [Instrumentation] Caused by: java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@e985754already registered!
[debug] [Instrumentation] 	at android.os.Parcel.createException(Parcel.java:2096)
[debug] [Instrumentation] 	at android.os.Parcel.readException(Parcel.java:2056)
[debug] [Instrumentation] 	at android.os.Parcel.readException(Parcel.java:2004)
[debug] [Instrumentation] 	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:427)
[debug] [Instrumentation] 	at android.app.UiAutomation.connect(UiAutomation.java:245)
[debug] [Instrumentation] 	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2185)
[debug] [Instrumentation] 	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
[debug] [Instrumentation] 	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
[debug] [Instrumentation] 	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
[debug] [Instrumentation] 	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
[debug] [Instrumentation] 	at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:33)
[debug] [Instrumentation] 	at io.appium.uiautomator2.model.internal.CustomUiDevice.<init>(CustomUiDevice.java:70)
[debug] [Instrumentation] 	at io.appium.uiautomator2.model.internal.CustomUiDevice.getInstance(CustomUiDevice.java:80)
[debug] [Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotStream.<clinit>(MjpegScreenshotStream.java:43)
[debug] [Instrumentation] 	... 32 more
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:52742/wd/hub/status] with no body
[WD Proxy] socket hang up
[debug] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [Instrumentation] INSTRUMENTATION_CODE: 0
[debug] [Instrumentation] The process has exited with code 0
[UiAutomator2] The instrumentation process has been unexpectedly terminated. Retrying UiAutomator2 startup (#1 of 1)

**ADB Logs**:
07-22 06:15:16.872 17064 17086 E appium  : java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@2b6f0b5already registered!
07-22 06:15:16.872 17064 17086 E appium  : 	at android.os.Parcel.createException(Parcel.java:2096)
07-22 06:15:16.872 17064 17086 E appium  : 	at android.os.Parcel.readException(Parcel.java:2056)
07-22 06:15:16.872 17064 17086 E appium  : 	at android.os.Parcel.readException(Parcel.java:2004)
07-22 06:15:16.872 17064 17086 E appium  : 	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:427)
07-22 06:15:16.872 17064 17086 E appium  : 	at android.app.UiAutomation.connect(UiAutomation.java:245)
07-22 06:15:16.872 17064 17086 E appium  : 	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2185)
07-22 06:15:16.872 17064 17086 E appium  : 	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
07-22 06:15:16.872 17064 17086 E appium  : 	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
07-22 06:15:16.872 17064 17086 E appium  : 	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
07-22 06:15:16.872 17064 17086 E appium  : 	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
07-22 06:15:16.872 17064 17086 E appium  : 	at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:40)
07-22 06:15:16.872 17064 17086 E appium  : 	at io.appium.uiautomator2.model.internal.CustomUiDevice.<init>(CustomUiDevice.java:75)
07-22 06:15:16.872 17064 17086 E appium  : 	at io.appium.uiautomator2.model.internal.CustomUiDevice.getInstance(CustomUiDevice.java:90)
07-22 06:15:16.872 17064 17086 E appium  : 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotStream.<clinit>(MjpegScreenshotStream.java:43)
07-22 06:15:16.872 17064 17086 E appium  : 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.<init>(MjpegScreenshotServer.java:41)
07-22 06:15:16.872 17064 17086 E appium  : 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.<init>(MjpegScreenshotServer.java:35)
07-22 06:15:16.872 17064 17086 E appium  : 	at io.appium.uiautomator2.server.ServerInstrumentation.startMjpegServer(ServerInstrumentation.java:241)
07-22 06:15:16.872 17064 17086 E appium  : 	at io.appium.uiautomator2.server.test.AppiumUiAutomator2Server.startServer(AppiumUiAutomator2Server.java:31)
07-22 06:15:16.872 17064 17086 E appium  : 	at java.lang.reflect.Method.invoke(Native Method)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
07-22 06:15:16.872 17064 17086 E appium  : 	at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.Suite.runChild(Suite.java:128)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.Suite.runChild(Suite.java:27)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
07-22 06:15:16.872 17064 17086 E appium  : 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
07-22 06:15:16.872 17064 17086 E appium  : 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
07-22 06:15:16.872 17064 17086 E appium  : 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
07-22 06:15:16.872 17064 17086 E appium  : 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2214)
07-22 06:15:16.872 17064 17086 E TestRunner: failed: startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)
07-22 06:15:16.872 17064 17086 E TestRunner: ----- begin exception -----
07-22 06:15:16.873 17064 17086 E TestRunner: java.lang.ExceptionInInitializerError
07-22 06:15:16.873 17064 17086 E TestRunner: 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.<init>(MjpegScreenshotServer.java:41)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.<init>(MjpegScreenshotServer.java:35)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at io.appium.uiautomator2.server.ServerInstrumentation.startMjpegServer(ServerInstrumentation.java:241)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at io.appium.uiautomator2.server.test.AppiumUiAutomator2Server.startServer(AppiumUiAutomator2Server.java:31)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2214)
07-22 06:15:16.873 17064 17086 E TestRunner: Caused by: java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@2b6f0b5already registered!
07-22 06:15:16.873 17064 17086 E TestRunner: 	at android.os.Parcel.createException(Parcel.java:2096)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at android.os.Parcel.readException(Parcel.java:2056)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at android.os.Parcel.readException(Parcel.java:2004)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:427)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at android.app.UiAutomation.connect(UiAutomation.java:245)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2185)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:40)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at io.appium.uiautomator2.model.internal.CustomUiDevice.<init>(CustomUiDevice.java:75)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at io.appium.uiautomator2.model.internal.CustomUiDevice.getInstance(CustomUiDevice.java:90)
07-22 06:15:16.873 17064 17086 E TestRunner: 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotStream.<clinit>(MjpegScreenshotStream.java:43)
07-22 06:15:16.873 17064 17086 E TestRunner: 	... 32 more
07-22 06:15:16.873 17064 17086 E TestRunner: ----- end exception -----
07-22 06:15:16.875 17064 17086 I TestRunner: finished: startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)

**Details**:
OS Name: "Mac OS X"
OS Version: "10.15.4"
Java Version: "14.0.1"
OS Arch: "x86_64"
Appium Version: 1.20.2
UIAutomator2 Server Version: 4.17.4

**Troubleshooting (Attempted)**:

I attempted some of the following workarounds but none of them helped.

1. Tried the following commands: _adb uninstall io.appium.uiautomator2.server_, _adb uninstall io.appium.uiautomator2.server.test_, _adb uninstall io.appium.settings_
2. Tried rebooting device multiple times
3. Tried changing "automationName" capability from "_uiautomator2_" to "_uiautomator1_" - However, I received an error saying "Uiautomator shut down unexpectedly"
4. Setting "skipServerInstallation" capability to true, and manually downloading and installing "_appium-uiautomator2-server-debug-androidTest.apk_" and "_appium-uiautomator2-server-v4.17.4.apk_"

Could you help troubleshoot this issue please? Please let me know if you need any additional details. I will be happy to provide.

Thank you!

**Comment by mykola-mokhnach** [comment]
https://www.programmersought.com/article/20325583212/

Basically this error has nothing to do with Appium itself. Make sure the device under test does not run any other UiAutomator-based processes as mentioned above before starting your automated tests

**Comment by ramgiteng** [comment]
Thank you @mykola-mokhnach for your tip. I will try it out and get back.

**Comment by ramgiteng** [comment]
@mykola-mokhnach 
So, I tried the following.
**Command**: adb shell pm list packages | grep uiautomator
**Output**:
package:io.appium.uiautomator2.server
_package:com.experitest.uiautomator.test_
package:io.appium.uiautomator2.server.test

So, I did 
**Command**: adb shell pm uninstall com.experitest.uiautomator.test
**Output**: Success
And it worked as expected. Appium was able to run the test on the real Android device as expected.

However, that package (com.experitest.uiautomator.test) reinstalls itself again after a few seconds. I would have to manually intervene and do "adb uninstall" at the point when uiautomator2server is invoked. I don't recall installing an app with this package name explicitly. Do you know how to ensure this package gets uninstalled for good?

**Comment by ramgiteng** [comment]
I managed to delete that other uiautomator2-server package by deleting a folder in the host machine. Now, it seems to work just fine. I will run a few tests to confirm that everything runs smoothly before closing this issue.

**Comment by ramgiteng** [comment]
Solved. Closing this issue. Thank you @mykola-mokhnach !
