### ISSUE TITLE
How to get the url of WebView?

### ISSUE THREAD

**Issue by Mygod** [appium/appium-uiautomator2-server#44]
There are multiple WebViews in an Activity and I want to know which URL/context corresponds to the WebView I selected. Is that possible?

**Comment by sravanmedarapu** [comment]
@Mygod `getContext()` will return your current context.

**Comment by Mygod** [comment]
I meant the webview I found using findElements.

**Comment by sravanmedarapu** [comment]
@Mygod Can you please more elaborate.

**Comment by Mygod** [comment]
Okay.

```
for (WebElement element : driver.findElementsByTagName("android.webkit.WebView"))
    if (someRules(element)) {
        String handle = /* element.getWindowHandle()? */;
        driver.context("WEBVIEW_" + getPackageName());
        driver.switchTo().window(handle);
        System.out.printf(driver.getCurrentUrl());
    }
```

**Comment by Mygod** [comment]
...did you get what I meant?

**Comment by sravanmedarapu** [comment]
Typically `getCurrentUrl()` proxies the request to chromedriver. There is nothing specific about uiautomator2-server. From my understanding Hybrid views doesn't contain/expose the urls.

**Comment by Mygod** [comment]
Which means there isn't any way to retrieve it right? Thanks.

**Comment by sravanmedarapu** [comment]
I believe you don't have url exposed to retrieve them. From my understanding if you hit `getCurrentUrl()` on webview you will html content of the webview.

**Comment by Mygod** [comment]
How do I `getCurrentUrl` on webview?

**Comment by sravanmedarapu** [comment]
@Mygod this is nothing specific about UiAutomator2. I don't have much idea on this, please raise in appropriate repo if you feel it is a valid.

**Comment by Mygod** [comment]
Okay thanks!

**Comment by Mygod** [comment]
Okay I opened an issue at appium but nobody seems to respond there. :cry:
