### ISSUE TITLE
appium does not return all android page source

### ISSUE THREAD

**Issue by lzus** [appium/appium-uiautomator2-server#448]
Hello every one,

from the second.jpeg,  appium could not return the right side page source(new view page source) while executing get source
only return the left side page source,

but in the second.jpeg, both left side and right side are on the same app with the same activity.

How to fix it?

<img width="631" alt="compare" src="https://user-images.githubusercontent.com/48306281/138255768-6bad3320-b8cf-47af-b325-3b8bf6a071ba.png">

https://user-images.githubusercontent.com/48306281/138265077-72d60973-7057-43c6-a09f-628653a441e0.mp4

first.log is the page source of first.jpeg
[first.log](https://github.com/appium/appium-uiautomator2-server/files/7388367/first.log)

second.log is the page source of second.jpeg
[second.log](https://github.com/appium/appium-uiautomator2-server/files/7388373/second.log)

**Comment by jlipps** [comment]
Load up that view manually and then run `adb shell uiautomator dump`. Do you see the elements you expect in the output file?

**Comment by KazuCocoa** [comment]
Did you try `enableMultiWindows: true` in settings api?
https://github.com/appium/appium-uiautomator2-driver#settings-api
