### ISSUE TITLE
How to start the server without starting an instrumentation 

### ISSUE THREAD

**Issue by stoefln** [appium/appium-uiautomator2-server#451]
Hi there,
This is rather a question than a bug report, but I didn't know where to ask if not here.
I've built the apks already and pushed and installed them on the device.
Now I would like to start the server.
I am not planning to use the whole appium setup, I am rather looking for a lightweight addon for my node app.
Can someone help me?

**Comment by jlipps** [comment]
Running the server on its own isn't really a supported mode of operation. If you want to see how it's done, it's best to look through the appium-uiautomator2-driver code (this is the code that starts the server running so it can speak to the server remotely). Basically the most relevant function is https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/uiautomator2.js#L267-L290
