### ISSUE TITLE
How to use latest appium uiautomator2 server to do automation test

### ISSUE THREAD

**Issue by sincethenn** [appium/appium-uiautomator2-server#474]
My appium server version  is 1.22.3. And the default appium uiautomator2 server's version is 4. 27.0.
I want to use latest 5.6 version of apk, manually install on device and set skipServerInstallation to true.
But actually, I cant start session normally.
Is there any way to use latest server apk to test?

**Comment by sincethenn** [comment]
Unlike io.appium.settings apk. After settings skipDeviceInitialization, app won't be installed and I could use latest apk to test.
uiautomator2 need both https://github.com/appium/appium-uiautomator2-driver and https://github.com/appium/appium-uiautomator2-server. Maybe I could only use the latest versiona when they match?

**Comment by suzhenyu006** [comment]
if i want to use uiautomator2-server version 5.7.0 what version can i use for java-client?

**Comment by KazuCocoa** [comment]
Client should not be an issue except for server handing.
If you'd like to manage Appium 2 server as the clients service class, the latest one might help. Otherwise any client versions can create a new session etc against Appium 2 in Java client
