### ISSUE TITLE
unable to install the uiautomator2 driver 

### ISSUE THREAD

**Issue by AYUSH-17** [appium/appium-uiautomator2-server#476]
@mykola-mokhnach 
appium : npm i -g appium@next
uiautomator2 : appium driver install uiautomator2 
OS Platform : Window 10
Error : 
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'Error: × Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code null.

STDOUT:

STDERR:

**Comment by KazuCocoa** [comment]
Perhaps uninstalling `~/.appium` once may help at that time.
