### ISSUE TITLE
Upgrade androidx.test.uiautomator:uiautomator to 2.3.0 to fix issue #398

### ISSUE THREAD

**Issue by xiaoPierre** [appium/appium-uiautomator2-server#490]
Hello, 

I ran into the same issue as https://github.com/appium/appium-uiautomator2-server/issues/398, and I see that [the issue submitted to google](https://issuetracker.google.com/issues/176710836) has been resolved in version 2.3.0 (here's the [release notes](https://developer.android.com/jetpack/androidx/releases/test-uiautomator#version_230_2)). 

Could we upgrade `androidx.test.uiautomator:uiautomator` to `2.3.0` to fix this long-lasting issue ? (It seems that write permission is not open for the repository..) Thanks in advance ! 

cc @mykola-mokhnach @KazuCocoa as you followed similar issues before.

**Comment by mykola-mokhnach** [comment]
feel free to open a PR. you need to fork the current repository in order to do that.

**Comment by mykola-mokhnach** [comment]
Also it's an alpha version. Do you think it is a good idea to include it into the release before it stabilizes?

**Comment by xiaoPierre** [comment]
Oh indeed it's still alpha01, probably it's better to wait for official stabilised release of 2.3.0 after several months, but I'll try and test if the fix works in a separate fork. 

(we're still using appium 1 so I hope it would easy to upgrade this library in appium 1 in our fork😃)

**Comment by xiaoPierre** [comment]
For info I just validated the fix with the new `2.3.0-alpha01` version with a local appium build, the buttons at the bottom of screen now have correct size. 

![image](https://user-images.githubusercontent.com/11867646/205680381-8f979abf-deed-45b1-b884-ed95f60346e4.png)

**Comment by Comeodore** [comment]
@KazuCocoa @xiaoPierre Any updates with it?

@xiaoPierre mb can u share how u install locally uiautomator 2.3.0 alpha
Can i use this with actual appium-uiautomator-server?

**Comment by KazuCocoa** [comment]
It looks like the lib changed to beta recently https://developer.android.com/jetpack/androidx/releases/test-uiautomator

**Comment by Comeodore** [comment]
> It looks like the lib changed to beta recently https://developer.android.com/jetpack/androidx/releases/test-uiautomator

Can u update lib in project to 2.3.0 beta?

**Comment by mykola-mokhnach** [comment]
Lets create a PR and see how the CI results look like with this beta

**Comment by KazuCocoa** [comment]
Basically, we've been waiting for the stable version release.

You can manually modify this branch directly and create the server as https://github.com/appium/appium-uiautomator2-server?tab=readme-ov-file#building-project . Then once you replace existing apk in https://github.com/appium/appium-uiautomator2-server/blob/50066dfc2f1435e53a364589a20d143561e9cb0d/index.js#L4 with the buit apk, the new apk will be picked up.

**Comment by Comeodore** [comment]
@KazuCocoa @mykola-mokhnach  UiAutomator devs depredecate getDefaultDisplay method
Now this is getDisplay(int), can u help me with changing it for my local using?
https://developer.android.com/reference/android/hardware/display/DisplayManager#getDisplay(int)

**Comment by KazuCocoa** [comment]
Do you mean https://developer.android.com/reference/android/view/WindowManager#getDefaultDisplay() ?

> This method was deprecated in API level 30.
> Use [Context#getDisplay()](https://developer.android.com/reference/android/content/Context#getDisplay()) instead.

https://developer.android.com/reference/android/content/Context#getDisplay()

**Comment by Comeodore** [comment]
@KazuCocoa 
With ur last changes on 2.3.0-beta01 version of uiautomator
<img width="1154" alt="image" src="https://github.com/appium/appium-uiautomator2-server/assets/55732318/ea10b0f1-ff4c-421f-be3e-a2dad4f0fc12">

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/appium-uiautomator2-server/pull/585 change helps. We haven't verified the latest version, so possibly the version has a compatibility issue.
Please report such new issues with newer dependencies we should update in https://github.com/appium/appium 's bug template.

**Comment by KazuCocoa** [comment]
For your case, it looks like the latest 2.3.0-beta01 package dropped the `getDefaultDisplay`, so all OS versions should follow https://github.com/appium/appium-uiautomator2-server/pull/585

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-server/pull/588 is a fix for the beta01

**Comment by Comeodore** [comment]
@KazuCocoa Thanks, its working, but now when i trying to click on element, has trouble like this

```java
E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot create UiObject2 instance with 'null' selector
E       Stacktrace:
E       io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Cannot create UiObject2 instance with 'null' selector
``` 

Any thoughts?

**Comment by KazuCocoa** [comment]
No, just we need to test well and fix them.
Early alpha maybe did not have such issues, so probably you could use early alpha version.

**Comment by Comeodore** [comment]
@KazuCocoa The same trouble on 2.3.0-alpha01

**Comment by KazuCocoa** [comment]
Then we should test the library carefully and update code. I guess we should update the base sdk version first, and wait for upcoming beta to see if it is intended changes in the lib or possible issue in the version.

**Comment by Comeodore** [comment]
@KazuCocoa Okay, please keep me posted, because fixing the screen size is very important for me (and judging by the many questions on various resources, not only for me)

**Comment by KazuCocoa** [comment]
Sure, then, please create a new issue in the main appium repository so that we can track issues easier for future investigation.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/19597 will be the primary (instead of this issue) place to link GitHub issues, but as https://github.com/appium/appium-uiautomator2-server/issues/490#issuecomment-1872568281, it would be helpful to create separate issue for different behavior. Then I'll keep linking them to the primary issue'
