### ISSUE TITLE
API_LEVEL_ACTUAL field removed in newer version of androidx.test.uiautomator

### ISSUE THREAD

**Issue by xiaoPierre** [appium/appium-uiautomator2-server#491]
This field has been removed in recent commit : 
https://cs.android.com/androidx/platform/frameworks/support/+/9401a648e44ba8c715d552a6fd6e84eca099b0ef:test/uiautomator/uiautomator/src/main/java/androidx/test/uiautomator/UiDevice.java;dlc=04a8195c39e0eb3f77b143c71ed0327c3ad63e5c

We should consider removing the usage of this field in the repo. 

https://github.com/appium/appium-uiautomator2-server/blob/28e0d4e2be403d05f0ad5276f85d56bc67da69f8/app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java#L74

**Comment by xiaoPierre** [comment]
Sure I'd love to help, just want to confirm, removing the usage of `API_LEVEL_ACTUAL` will make it not support android api level 23 anymore because I plan to simplify the following code. Does it look good for you ? 

https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java#L106

**Comment by mykola-mokhnach** [comment]
I would rather simply change the used constant to Build.VERSION.SDK_INT, like Google did. There is no reason for me to cut lower APIs support
