### ISSUE TITLE
Can I add an API to obtain the adb shell uiautomator dump? The wechat mini program I'm working on needs to obtain the dump very much.

### ISSUE THREAD

**Issue by TesterWa** [appium/appium-uiautomator2-server#496]
Can I add an API to obtain the adb shell uiautomator dump? The wechat mini program I'm working on needs to obtain the dump very much.

**Comment by KazuCocoa** [comment]
You can call an arbitrary `adb shell` over https://github.com/appium/appium-uiautomator2-driver/#mobile-shell

**Comment by TesterWa** [comment]
> `adb shell`您可以通过https://github.com/appium/appium-uiautomator2-driver/#mobile-shell调用任意[](https://github.com/appium/appium-uiautomator2-driver/#mobile-shell)

Since the instance of uiautomator has been initialized by the appium reflection, the command line tool of UIautomator can no longer be called through mobile: shell.

**Comment by KazuCocoa** [comment]
Then, you can use `appium:disableSuppressAccessibilityService` to not suppress accessibility service by Android framework

**Comment by TesterWa** [comment]
> 然后，您可以使用`appium:disableSuppressAccessibilityService`Android 框架不抑制辅助功能服务

So does appium desktop 1.22.0 support this configuration?

**Comment by KazuCocoa** [comment]
i think so
