### ISSUE TITLE
From element, could not getting value of "checked" attribute.

### ISSUE THREAD

**Issue by jjangah** [appium/appium-uiautomator2-server#52]
Hello, I have trouble with getting attribute from element.

My environment : Android 6.0, Appium 1.6.3, uiautomator2

I tired to get value of "checked" attribute of CheckBox widget, but had error.

Here is my python code.

```
el = self.driver.find_element_by_xpath("")
logger.info(el.get_attribute("checked") )
```

and the error
```
....
File ".../venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 144,
in get_attribute if name != 'value' and attributeValue.lower() in ('true', 'false'): 
AttributeError: 'bool' object has no attribute 'lower'
....

```
So, I patched webelement.py file and it seems working now.
However, I don't know where to report this problem to fix this error. 
Should I report this to selenium? or is uiautomator2 sends boolean value?

Please check this issue out. 
Thank you!

**Comment by ole-vegard** [comment]
I think this is the same as 
https://github.com/appium/appium-uiautomator2-server/issues/55, which was fixed in https://github.com/appium/appium-uiautomator2-server/pull/56

**Comment by zhixau** [comment]
This issue also happened on iOS app.

I use the appium 1.6.5, selenium 3.3.0, Appium-Python-Client 0.24, and try to get the 'enabled' attribute of a button. Then get the same error as jjangah.

Is it the issue for appium?
