### ISSUE TITLE
Returning boolean value in get element atrribute

### ISSUE THREAD

**Issue by devstrat** [appium/appium-uiautomator2-server#55]
Hi folks, 
I have a question regarding this:
https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/handler/GetElementAttribute.java#L41

I've seen some problems with UIAUTOMATOR2 returning bool instead of string (it was causing python webdriver bindings to crash). 
According to spec bool attributes should be return as strings as well:
https://w3c.github.io/webdriver/webdriver-spec.html#get-element-attribute
> 13.2 Get Element Attribute
> ...
> **If name is a boolean attribute**
> "true" (**string**) if the element has the attribute, otherwise null.
> 
> Otherwise
> The result of getting an attribute by name name.

Should this be fixed?

**Comment by jlipps** [comment]
yeah could be a potential bug, what do you think @sravanmedarapu?

**Comment by sravanmedarapu** [comment]
Yeah, this should be fixed.

**Comment by ole-vegard** [comment]
This is fixed in https://github.com/appium/appium-uiautomator2-server/pull/56, right?

**Comment by devstrat** [comment]
@ole-vegard Correct
