### ISSUE TITLE
Is there any potentail risk that I change [waitForIdleTimeout] config to small value？

### ISSUE THREAD

**Issue by MilesYuanCN** [appium/appium-uiautomator2-server#574]
We encounter a problem that [find_element] does not return element instantly when the app is continuious changing. So we want to change the waitForIdleTimeout value to a smaller one (default should be 10s).
Would this lead something wrong happen?
What is the purpose of [getUiDevice().waitForIdle(timeoutMs);]？

**Comment by mykola-mokhnach** [comment]
> Would this lead something wrong happen?

I wouldn't worry about the automation test itself, especially if timeouts are used to look for elements. 
It is more about the application under test itself. The fact it locks the main thread for too long means it has an increased CPU usage and kills phone battery faster. Generally a properly designed mobile application should be idling most of the time it does not respond to user actions.

**Comment by MilesYuanCN** [comment]
> > Would this lead something wrong happen?
> 
> I wouldn't worry about the automation test itself, especially if timeouts are used to look for elements. It is more about the application under test itself. The fact it locks the main thread for too long means it has an increased CPU usage and kills phone battery faster. Generally a properly designed mobile application should be idling most of the time it does not respond to user actions.

Thank you for replay.
The business scenario in question is video playback, where some controls update every 300ms (which is less than the threshold of 500ms set for determining the Idle state). Therefore, the main thread is not constantly blocked.

We would change the [waitForIdleTimeout] param to 1000 in appium driver to solve the problem。
