### ISSUE TITLE
How to configure appium 1.6.4 switch to UIAutomator2 ?

### ISSUE THREAD

**Issue by robertluo1949** [appium/appium-uiautomator2-server#58]
i need to use new UIAutomator2 on my appium project.

C:\Users\shuiboluo>appium-doctor
info AppiumDoctor Appium Doctor v.1.2.5
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ ANDROID_HOME is set to: D:\automatic-soft\Android\sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\ORACLE\jdk1.8.131
info AppiumDoctor  ✔ adb exists at: D:\automatic-soft\Android\sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: D:\automatic-soft\Android\sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: D:\automatic-soft\Android\sdk\tools\emulator.exe
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

**Comment by alvy54** [comment]
You just need to set automationName = 'uiautomator2' in your capabilities.

**Comment by robertluo1949** [comment]
@alvy54  it is OK。
        desired_caps = {}
        desired_caps['platformName'] = 'Android'
        desired_caps['platformVersion'] = '6.0'
        desired_caps['deviceName'] = '192.168.89.101:5555'
## #         desired_caps['automationName'] = 'uiautomator2'

**Comment by jlipps** [comment]
yep, that's the way!

**Comment by badjujugurl** [comment]
Where do you set the #desired_caps.. command from above?

**Comment by imurchie** [comment]
Wherever you are starting the session, you will have your desired capabilities. Just add the `automationName` capability.
