### ISSUE TITLE
The 'duration' argument of 'performActions' API does not affect on Android WebView ( Appium 1.22.*, Appium 2.5.1 )

### ISSUE THREAD

**Issue by kimduquan01** [appium/appium-uiautomator2-server#623]
**Reproduce steps:**
 - on Android device, open an application that use embedded WebView 
 - call 'switchToContext' API to switch to a web view context
 - call the 'performActions' API with the follow JSON input:
 - `{
	"actions": [
		{
			"id": "touch",
			"type": "pointer",
			"parameters": {
				"pointerType": "touch"
			},
			"actions": [
				{
					"duration": 0,
					"x": 0,
					"y": 0,
					"type": "pointerMove",
					"origin": "viewport"
				},
				{
					"duration": 0,
					"x": 180,
					"y": 378,
					"type": "pointerMove",
					"origin": "viewport"
				},
				{
					"button": 0,
					"type": "pointerDown"
				},
				{
					"duration": 500,
					"x": -90,
					"y": -189,
					"type": "pointerMove",
					"origin": "pointer"
				},
				{
					"button": 0,
					"type": "pointerUp"
				}
			]
		}
	]
}`

**Observes:**
 - The application is slide but the 'duration' does not affect so that the slide action is perform too fast

**Notes:**
 - The issue does not occur on the same device and application if switch to 'NATIVE_APP' context before calling 'performActions' API

**Comment by jlipps** [comment]
If you're in web mode then the action is being handled by chromedriver, not Appium, so there's probably not much we can do about it.
