### ISSUE TITLE
当我使用无线调试的时候，请求速度特别慢

### ISSUE THREAD

**Issue by zzu402** [appium/appium-uiautomator2-server#635]
1.当我使用usb连接时候，能够快速地获取各种元素
2.但是当我使用无线调试的时候，需要两百多秒才能返回。
请问这是为什么？有什么解决方法？

**Comment by KazuCocoa** [comment]
Please post in English (just applying a translation app is fine)
https://discuss.appium.io/ is a good place to ask a general question
