### ISSUE TITLE
Failed to capture Screen Shot

### ISSUE THREAD

**Issue by GospelHW** [appium/appium-uiautomator2-server#70]
public static String screenshot(String filePath) throws JSONException {
        JSONObject jsonObject = new JSONObject();
        return get(baseUrl + "/screenshot");
    }

**Comment by jlipps** [comment]
what failed exactly? please include a full set of logs

**Comment by GospelHW** [comment]
I'm sorry, but please close this question. Because it turned out that there was no storage authority after screenshot.
