### ISSUE TITLE
The API 24 above requires dynamic request permission, how to write the test in app-uiautomaor2-server?

### ISSUE THREAD

**Issue by GospelHW** [appium/appium-uiautomator2-server#71]
The API 24 above requires dynamic request permission, how to write the test in app-uiautomaor2-server? (Permission denied)

**Comment by GospelHW** [comment]
Android 5.1 or above requires dynamic request for memory card read-write access. How to write the test in app-uiautomaor2-server?So that's ok

**Comment by jlipps** [comment]
For usage questions and getting started questions, please reach out for help on our forums (discuss.appium.io). This issue tracker is for reporting bugs.
