### ISSUE TITLE
Xpath works with UIautomator but same xpath does not work with UIautomator2 

### ISSUE THREAD

**Issue by abhasingh1** [appium/appium-uiautomator2-server#72]
xpath which does not work with Uiautomator2
@findby(xpath="//android.widget.EditText[@resource-id='com.test.android.app:id/edit_text'][@Naf='true']")

Please help.

Appium version- 1.6.5(command line)
uiautomator2 version-
appium-uiautomator2-driver@0.4.2
appium-uiautomator2-server@0.1.8

**Comment by imurchie** [comment]
What does "does not work" mean? It doesn't find anything? Finds the wrong thing? Crashes?

Please attach the full Appium server logs, as a link to a [gist](https://gist.github.com). It might also be helpful to see the page source when you are trying to do the search.

**Comment by livastar** [comment]
@imurchie simular situation.
Appium verision: v1.6.6-beta.4
Test Case is simple. Open app, verify that status bar is present.
With automationName = appium it's working, the element is found.
While using UIAutomator2 element is not found.

**Comment by imurchie** [comment]
Ok. Can you provide the source at the point you are trying the xpath search? And the full server logs as a link to a [gist](https://gist.github.com)?

**Comment by abhasingh1** [comment]
I get NosuchElement exception.a attached logs
[pagesource.txt](https://github.com/appium/appium-uiautomator2-server/files/1198095/pagesource.txt)


[appiumlog.txt](https://github.com/appium/appium-uiautomator2-server/files/1198093/appiumlog.txt)

**Comment by imurchie** [comment]
I cannot read these files. Please attach as links to [gists](https://gist.github.com).

**Comment by abhasingh1** [comment]
https://gist.github.com/abhasingh1/1cda2e4c80c42e71c39860cd81deabc6/revisions

**Comment by livastar** [comment]
In my case I'm searching the element through ID, but the same thing. Using appium as automatioName,Test case is passing, but neither with UIAutomator2

**Comment by abhasingh1** [comment]
I was able to solve this using a different inspector and using xpath.
