### ISSUE TITLE
special characters like â cannot be entered it is giving permission error 

### ISSUE THREAD

**Issue by abhasingh1** [appium/appium-uiautomator2-server#73]
Getting the below error when I am trying to enter special characters like "â". 

[debug] [ADB] Running '/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ce051605646b143c05","shell","input","text","aaaâ"]
    **# [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Library/Android/sdk/platform-tools/adb -P 5037 -s ce051605646b143c05 shell input text â' exited with code 137'; Stderr: 'sh: resetreason: can't execute: Permission denied'; Code: '137'
        at ADB.execFunc$ (../../../lib/tools/system-calls.js:228:13)**
        at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
        at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
        at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
        at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    [HTTP] <-- POST /wd/hub/session/8887e708-05a1-4809-94c1-d842f713b2ca/appium/element/b448c050-c92e-4a8c-a731-cc74155885a5/value 500 1383 ms - 425

**Comment by imurchie** [comment]
Android requires special capabilities in order to handle unicode characters. Please see https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/unicode.md#android

**Comment by abhasingh1** [comment]
I tried Unicode capability as well. I get the same error when I use Unicode capability.
Thanks

**Comment by imurchie** [comment]
Please provide the full Appium server logs for a run using the `unicodeKeyboard` capability (logs as a link to a [gist](https://gist.github.com)).

**Comment by abhasingh1** [comment]
https://gist.github.com/abhasingh1/bdc394aefc96be331b6019e9ece7d590

**Comment by imurchie** [comment]
Oh. Yes, setting the value directly (using `driver.setValue`) will fail in this case. That method is specifically provided to bypass everything and use the lowest level input possible, which only works for ASCII.

You need to use the `driver.sendKeys` method to actually go through the Unicode IME and input the characters.

**Comment by abhasingh1** [comment]
Thanks it worked

**Comment by imurchie** [comment]
Excellent!
